<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: salto/longrunning/v1/operation.proto

namespace Saltoapis\Longrunning\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The request message for
 * [`OperationService.DeleteOperation`][salto.longrunning.v1.OperationService.DeleteOperation].
 *
 * Generated from protobuf message <code>salto.longrunning.v1.DeleteOperationRequest</code>
 */
class DeleteOperationRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The resource name of the operation to be deleted. For example:
     * `operations/01ds5r5cbjr9hvke5f6c5s7nm0`.
     * Format: operations/{operation}
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           The resource name of the operation to be deleted. For example:
     *           `operations/01ds5r5cbjr9hvke5f6c5s7nm0`.
     *           Format: operations/{operation}
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Saltoapis\Longrunning\V1\Operation::initOnce();
        parent::__construct($data);
    }

    /**
     * The resource name of the operation to be deleted. For example:
     * `operations/01ds5r5cbjr9hvke5f6c5s7nm0`.
     * Format: operations/{operation}
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * The resource name of the operation to be deleted. For example:
     * `operations/01ds5r5cbjr9hvke5f6c5s7nm0`.
     * Format: operations/{operation}
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

}

