<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: salto/longrunning/v1/operation.proto

namespace Saltoapis\Longrunning\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The request message for
 * [`OperationService.ListOperations`][salto.longrunning.v1.OperationService.ListOperations].
 *
 * Generated from protobuf message <code>salto.longrunning.v1.ListOperationsRequest</code>
 */
class ListOperationsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The maximum number of items to return.
     *
     * Generated from protobuf field <code>int32 page_size = 1;</code>
     */
    protected $page_size = 0;
    /**
     * The `next_page_token` value returned from a previous `List` request, if
     * any.
     *
     * Generated from protobuf field <code>string page_token = 2;</code>
     */
    protected $page_token = '';
    /**
     * A filter that chooses which operations to return. The maximum
     * length of the filter is 20000 characters.
     *
     * Generated from protobuf field <code>string filter = 3;</code>
     */
    protected $filter = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $page_size
     *           The maximum number of items to return.
     *     @type string $page_token
     *           The `next_page_token` value returned from a previous `List` request, if
     *           any.
     *     @type string $filter
     *           A filter that chooses which operations to return. The maximum
     *           length of the filter is 20000 characters.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Saltoapis\Longrunning\V1\Operation::initOnce();
        parent::__construct($data);
    }

    /**
     * The maximum number of items to return.
     *
     * Generated from protobuf field <code>int32 page_size = 1;</code>
     * @return int
     */
    public function getPageSize()
    {
        return $this->page_size;
    }

    /**
     * The maximum number of items to return.
     *
     * Generated from protobuf field <code>int32 page_size = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPageSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->page_size = $var;

        return $this;
    }

    /**
     * The `next_page_token` value returned from a previous `List` request, if
     * any.
     *
     * Generated from protobuf field <code>string page_token = 2;</code>
     * @return string
     */
    public function getPageToken()
    {
        return $this->page_token;
    }

    /**
     * The `next_page_token` value returned from a previous `List` request, if
     * any.
     *
     * Generated from protobuf field <code>string page_token = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPageToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->page_token = $var;

        return $this;
    }

    /**
     * A filter that chooses which operations to return. The maximum
     * length of the filter is 20000 characters.
     *
     * Generated from protobuf field <code>string filter = 3;</code>
     * @return string
     */
    public function getFilter()
    {
        return $this->filter;
    }

    /**
     * A filter that chooses which operations to return. The maximum
     * length of the filter is 20000 characters.
     *
     * Generated from protobuf field <code>string filter = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setFilter($var)
    {
        GPBUtil::checkString($var, True);
        $this->filter = $var;

        return $this;
    }

}

