<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: salto/nebula/encoder/v1/encoder.proto

namespace Saltoapis\Nebula\Encoder\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The request message for [`BindEncoder`][salto.nebula.encoder.v1.EncoderService.BindEncoder]
 *
 * Generated from protobuf message <code>salto.nebula.encoder.v1.BindEncoderRequest</code>
 */
class BindEncoderRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The resource name of the encoder to be bound. For example:
     * `installations/surelock-homes-hq/encoders/baker-street-entrance`.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Globally unique identifier that is used across all devices manufactured
     * by SALTO, including gateways, extenders, electronic locks and so on.
     *
     * Generated from protobuf field <code>string device_id = 2;</code>
     */
    protected $device_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           The resource name of the encoder to be bound. For example:
     *           `installations/surelock-homes-hq/encoders/baker-street-entrance`.
     *     @type string $device_id
     *           Globally unique identifier that is used across all devices manufactured
     *           by SALTO, including gateways, extenders, electronic locks and so on.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Saltoapis\Nebula\Encoder\V1\Encoder::initOnce();
        parent::__construct($data);
    }

    /**
     * The resource name of the encoder to be bound. For example:
     * `installations/surelock-homes-hq/encoders/baker-street-entrance`.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * The resource name of the encoder to be bound. For example:
     * `installations/surelock-homes-hq/encoders/baker-street-entrance`.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Globally unique identifier that is used across all devices manufactured
     * by SALTO, including gateways, extenders, electronic locks and so on.
     *
     * Generated from protobuf field <code>string device_id = 2;</code>
     * @return string
     */
    public function getDeviceId()
    {
        return $this->device_id;
    }

    /**
     * Globally unique identifier that is used across all devices manufactured
     * by SALTO, including gateways, extenders, electronic locks and so on.
     *
     * Generated from protobuf field <code>string device_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDeviceId($var)
    {
        GPBUtil::checkString($var, True);
        $this->device_id = $var;

        return $this;
    }

}

