<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: salto/nebula/encoder/v1/encoder.proto

namespace Saltoapis\Nebula\Encoder\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * The response message for [ListEncoders][salto.nebula.encoder.v1.EncoderService.ListEncoders]
 *
 * Generated from protobuf message <code>salto.nebula.encoder.v1.ListEncodersResponse</code>
 */
class ListEncodersResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The field name should match the noun `encoders` in the method name. There
     * will be a maximum number of items returned based on the `page_size` field
     * in the request.
     *
     * Generated from protobuf field <code>repeated .salto.nebula.encoder.v1.Encoder encoders = 1;</code>
     */
    private $encoders;
    /**
     * Token to retrieve the next page of results, or empty if there are no more
     * results in the list.
     *
     * Generated from protobuf field <code>string next_page_token = 2;</code>
     */
    protected $next_page_token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Saltoapis\Nebula\Encoder\V1\Encoder[] $encoders
     *           The field name should match the noun `encoders` in the method name. There
     *           will be a maximum number of items returned based on the `page_size` field
     *           in the request.
     *     @type string $next_page_token
     *           Token to retrieve the next page of results, or empty if there are no more
     *           results in the list.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Saltoapis\Nebula\Encoder\V1\Encoder::initOnce();
        parent::__construct($data);
    }

    /**
     * The field name should match the noun `encoders` in the method name. There
     * will be a maximum number of items returned based on the `page_size` field
     * in the request.
     *
     * Generated from protobuf field <code>repeated .salto.nebula.encoder.v1.Encoder encoders = 1;</code>
     * @return RepeatedField<\Saltoapis\Nebula\Encoder\V1\Encoder>
     */
    public function getEncoders()
    {
        return $this->encoders;
    }

    /**
     * The field name should match the noun `encoders` in the method name. There
     * will be a maximum number of items returned based on the `page_size` field
     * in the request.
     *
     * Generated from protobuf field <code>repeated .salto.nebula.encoder.v1.Encoder encoders = 1;</code>
     * @param \Saltoapis\Nebula\Encoder\V1\Encoder[] $var
     * @return $this
     */
    public function setEncoders($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Saltoapis\Nebula\Encoder\V1\Encoder::class);
        $this->encoders = $arr;

        return $this;
    }

    /**
     * Token to retrieve the next page of results, or empty if there are no more
     * results in the list.
     *
     * Generated from protobuf field <code>string next_page_token = 2;</code>
     * @return string
     */
    public function getNextPageToken()
    {
        return $this->next_page_token;
    }

    /**
     * Token to retrieve the next page of results, or empty if there are no more
     * results in the list.
     *
     * Generated from protobuf field <code>string next_page_token = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNextPageToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->next_page_token = $var;

        return $this;
    }

}

