<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: salto/nebula/encoder/v1/encoder.proto

namespace Saltoapis\Nebula\Encoder\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The metadata message for [`ReadKey`][salto.nebula.device.v1.EncoderService.ReadKey]
 *
 * Generated from protobuf message <code>salto.nebula.encoder.v1.ReadKeyMetadata</code>
 */
class ReadKeyMetadata extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Saltoapis\Nebula\Encoder\V1\Encoder::initOnce();
        parent::__construct($data);
    }

}

