"""
Generated by proto-builder (php). DO NOT EDIT.

This file contains information collected during the code generation process.
It contains the protoc plugin versions used to generate the code, which is
useful during the build of those classes to define required dependencies.

It also contains a list of Bazel packages defined in the project.
"""

# used versions
API_LINTER_SHA="3615a346efc678a6110bdbd0b770f2d33adaaea6"
GITHUB_CLI_VERSION="2.30.0"
GOLANG_VERSION="1.22.2"
GRPC_CSHARP_VERSION="2.62.0"
GRPC_GO_GENERATOR_VERSION="1.2.0"
GRPC_GO_VERSION="1.60.0"
GRPC_JAVA_VERSION="1.63.0"
GRPC_KOTLIN_VERSION="1.2.0"
GRPC_SWIFT_VERSION="1.23.0"
GRPC_VERSION="1.63.0"
GRPC_WEB_VERSION="1.5.0"
NODEJS_VERSION="18.16.1"
PROTOBUF_JAVASCRIPT_VERSION="3.21.2"
PROTOBUF_VERSION="26.1"
PROTOC_BRIDGE_GENERATOR_SHA="fe0a77aca74329a0ab6fe73cc43442e037b8f1e7"
PROTOC_CONNECT_ES_VERSION="1.3.0"
PROTOC_ES_VERSION="1.3.1"
PROTOC_GO_GENERATOR_VERSION="1.32.0"
PROTOC_GO_JSON_GENERATOR_VERSION="49905733154f04e47d685de62c2cc2b72613b69e"
PROTOC_GRPC_GATEWAY_GENERATOR_VERSION="2.19.0"
PROTOC_MD_GENERATOR_SHA="090a67afd0ad11a2e2785e40dc7dd0fdbf01eaec"
PROTOC_MERGER_GENERATOR_SHA="2465a7eeba334148d53cec4a32f9304bc3b5f73e"
PROTOC_METADATA_GENERATOR_SHA="2e586c2c4623384d0b25a49adb0364eb8a899ed4"
PROTOC_TS_GENERATOR_SHA="735cb2ec9c94c4a4b2eb91dc36d4bf4e4da25a48"
PROTOC_VALIDATE_GENERATOR_SHA="57e0ec18ccb754b8e9df37a3d0e58eb5b7dead4a"
PROTOLOCK_VERSION="0.16.0"
PROTOSON_SHA="f31989050d43e5041d812cfebf42eb04287cc0b8"
SRPC_GO_SHA="d2b952e52065dd607c6b19ad495e946f87555e2a"
SRPC_VERSION="0.0.0-alpha.49"
SWIFT_VERSION="5.10"
VALE_VERSION="2.27.0"

php_projects = [
    '//src/Saltoapis/Nebula/AccessPointGroup/V1',
    '//src/Saltoapis/Nebula/File/V1',
    '//src/Saltoapis/Nebula/Iam/V1',
    '//src/Saltoapis/Nebula/Unit/V1',
    '//src/Saltoapis/Type',
    '//src/Google/Rpc',
    '//src/Saltoapis/Nebula/DigitalKey/V1',
    '//src/Saltoapis/Nebula/Installation/V1',
    '//src/Saltoapis/Nebula/Type',
    '//src/Saltoapis/Longrunning/V1',
    '//src/Saltoapis/Nebula/AccessPoint/V1',
    '//src/Saltoapis/Nebula/AccessRight/V1',
    '//src/Saltoapis/Nebula/Calendar/V1',
    '//src/Saltoapis/Nebula/Controller/V1',
    '//src/Saltoapis/Nebula/Device/V1',
    '//src/Saltoapis/Nebula/ElectronicLock/V1',
    '//src/Saltoapis/Nebula/Encoder/V1',
    '//src/Saltoapis/Nebula/Extender/V1',
    '//src/Saltoapis/Nebula/Gateway/V1',
    '//src/Saltoapis/Nebula/IntercomAdaptor/V1',
    '//src/Saltoapis/Nebula/OpeningModeSchedule/V1',
    '//src/Saltoapis/Nebula/User/V1',
    '//src/Saltoapis/Nebula/Event/V1',
]
