<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: salto/type/color.proto

namespace GPBMetadata\Saltoapis\Type;

class Color
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\x9E\x02\x0A\x16salto/type/color.proto\x12\x0Asalto.type\"O\x0A\x05Color\x12\x0B\x0A\x03red\x18\x01 \x01(\x02\x12\x0D\x0A\x05green\x18\x02 \x01(\x02\x12\x0C\x0A\x04blue\x18\x03 \x01(\x02\x12\x12\x0A\x05alpha\x18\x04 \x01(\x02H\x00\x88\x01\x01B\x08\x0A\x06_alphaB\x9E\x01\x0A\x12com.saltoapis.typeB\x0AColorProtoP\x01Z;github.com/saltoapis-internal/saltoapis-go/type/color;color\xAA\x02\x0ESaltoapis.Type\xCA\x02\x0ESaltoapis\\Type\xE2\x02\x1AGPBMetadata\\Saltoapis\\Typeb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

