<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: salto/nebula/device/v1/device.proto

namespace GPBMetadata\Saltoapis\Nebula\Device\V1;

class Device
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        \GPBMetadata\Saltoapis\Nebula\Type\DeviceType::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\x82\x09\x0A#salto/nebula/device/v1/device.proto\x12\x16salto.nebula.device.v1\x1A#salto/nebula/type/device_type.proto\"\xE5\x02\x0A\x06Device\x12\x0C\x0A\x04name\x18\x01 \x01(\x09\x12\x14\x0A\x0Cdisplay_name\x18\x02 \x01(\x09\x12\x16\x0A\x09device_id\x18\x03 \x01(\x09H\x01\x88\x01\x01\x122\x0A\x0Bdevice_type\x18\x04 \x01(\x0E2\x1D.salto.nebula.type.DeviceType\x12\x0E\x0A\x06source\x18\x05 \x01(\x09\x12\x11\x0A\x07gateway\x18\x06 \x01(\x09H\x00\x12\x12\x0A\x08extender\x18\x07 \x01(\x09H\x00\x12\x10\x0A\x08outdated\x18\x08 \x01(\x08\x12\x16\x0A\x09connected\x18\x09 \x01(\x08H\x02\x88\x01\x01\x12\x18\x0A\x0Blow_battery\x18\x0A \x01(\x08H\x03\x88\x01\x01\x123\x0A\x0Flast_event_time\x18\x0B \x01(\x0B2\x1A.google.protobuf.TimestampB\x0F\x0A\x0Dparent_deviceB\x0C\x0A\x0A_device_idB\x0C\x0A\x0A_connectedB\x0E\x0A\x0C_low_battery\" \x0A\x10GetDeviceRequest\x12\x0C\x0A\x04name\x18\x01 \x01(\x09\"m\x0A\x12ListDevicesRequest\x12\x0E\x0A\x06parent\x18\x01 \x01(\x09\x12\x11\x0A\x09page_size\x18\x02 \x01(\x05\x12\x12\x0A\x0Apage_token\x18\x03 \x01(\x09\x12\x0E\x0A\x06filter\x18\x04 \x01(\x09\x12\x10\x0A\x08order_by\x18\x05 \x01(\x09\"s\x0A\x13ListDevicesResponse\x12/\x0A\x07devices\x18\x01 \x03(\x0B2\x1E.salto.nebula.device.v1.Device\x12\x17\x0A\x0Fnext_page_token\x18\x02 \x01(\x09\x12\x12\x0A\x0Atotal_size\x18\x03 \x01(\x052\xCE\x01\x0A\x0DDeviceService\x12U\x0A\x09GetDevice\x12(.salto.nebula.device.v1.GetDeviceRequest\x1A\x1E.salto.nebula.device.v1.Device\x12f\x0A\x0BListDevices\x12*.salto.nebula.device.v1.ListDevicesRequest\x1A+.salto.nebula.device.v1.ListDevicesResponseB\xD6\x01\x0A\x1Ecom.saltoapis.nebula.device.v1B\x0BDeviceProtoP\x01ZBgithub.com/saltoapis-internal/saltoapis-go/nebula/device/v1;device\xAA\x02\x1ASaltoapis.Nebula.Device.V1\xCA\x02\x1ASaltoapis\\Nebula\\Device\\V1\xE2\x02&GPBMetadata\\Saltoapis\\Nebula\\Device\\V1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

