<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: salto/nebula/unit/v1/unit.proto

namespace Saltoapis\Nebula\Unit\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The response message for [`ListPolicies`][salto.nebula.unit.v1.UnitService.ListPolicies]
 *
 * Generated from protobuf message <code>salto.nebula.unit.v1.ListPoliciesResponse</code>
 */
class ListPoliciesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The field name should match the noun `policies` in the method name.
     * There will be a maximum number of items returned based on the `page_size`
     * field in the request.
     *
     * Generated from protobuf field <code>repeated .salto.nebula.unit.v1.Policy policies = 1;</code>
     */
    private $policies;
    /**
     * Token to retrieve the next page of results, or empty if there are no more
     * results in the list.
     *
     * Generated from protobuf field <code>string next_page_token = 2;</code>
     */
    protected $next_page_token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Saltoapis\Nebula\Unit\V1\Policy>|\Google\Protobuf\Internal\RepeatedField $policies
     *           The field name should match the noun `policies` in the method name.
     *           There will be a maximum number of items returned based on the `page_size`
     *           field in the request.
     *     @type string $next_page_token
     *           Token to retrieve the next page of results, or empty if there are no more
     *           results in the list.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Saltoapis\Nebula\Unit\V1\Unit::initOnce();
        parent::__construct($data);
    }

    /**
     * The field name should match the noun `policies` in the method name.
     * There will be a maximum number of items returned based on the `page_size`
     * field in the request.
     *
     * Generated from protobuf field <code>repeated .salto.nebula.unit.v1.Policy policies = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPolicies()
    {
        return $this->policies;
    }

    /**
     * The field name should match the noun `policies` in the method name.
     * There will be a maximum number of items returned based on the `page_size`
     * field in the request.
     *
     * Generated from protobuf field <code>repeated .salto.nebula.unit.v1.Policy policies = 1;</code>
     * @param array<\Saltoapis\Nebula\Unit\V1\Policy>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPolicies($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Saltoapis\Nebula\Unit\V1\Policy::class);
        $this->policies = $arr;

        return $this;
    }

    /**
     * Token to retrieve the next page of results, or empty if there are no more
     * results in the list.
     *
     * Generated from protobuf field <code>string next_page_token = 2;</code>
     * @return string
     */
    public function getNextPageToken()
    {
        return $this->next_page_token;
    }

    /**
     * Token to retrieve the next page of results, or empty if there are no more
     * results in the list.
     *
     * Generated from protobuf field <code>string next_page_token = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNextPageToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->next_page_token = $var;

        return $this;
    }

}

