<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: salto/nebula/unit/v1/unit.proto

namespace Saltoapis\Nebula\Unit\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Representation of a unit resource inside the API
 *
 * Generated from protobuf message <code>salto.nebula.unit.v1.Unit</code>
 */
class Unit extends \Google\Protobuf\Internal\Message
{
    /**
     * Resource name of the unit. It must have the format
     * `installations/&#42;&#47;units/&#42;`, for example:
     * `installations/surelock-homes-hq/units/101`.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Display name.
     *
     * Generated from protobuf field <code>string display_name = 2;</code>
     */
    protected $display_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           Resource name of the unit. It must have the format
     *           `installations/&#42;&#47;units/&#42;`, for example:
     *           `installations/surelock-homes-hq/units/101`.
     *     @type string $display_name
     *           Display name.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Saltoapis\Nebula\Unit\V1\Unit::initOnce();
        parent::__construct($data);
    }

    /**
     * Resource name of the unit. It must have the format
     * `installations/&#42;&#47;units/&#42;`, for example:
     * `installations/surelock-homes-hq/units/101`.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Resource name of the unit. It must have the format
     * `installations/&#42;&#47;units/&#42;`, for example:
     * `installations/surelock-homes-hq/units/101`.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Display name.
     *
     * Generated from protobuf field <code>string display_name = 2;</code>
     * @return string
     */
    public function getDisplayName()
    {
        return $this->display_name;
    }

    /**
     * Display name.
     *
     * Generated from protobuf field <code>string display_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDisplayName($var)
    {
        GPBUtil::checkString($var, True);
        $this->display_name = $var;

        return $this;
    }

}

