<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: salto/nebula/destination/v1/destination.proto

namespace Saltoapis\Nebula\Destination\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The response message for [`BatchGetDestinations`][salto.nebula.destination.v1.DestinationService.BatchGetDestinations]
 *
 * Generated from protobuf message <code>salto.nebula.destination.v1.BatchGetDestinationsResponse</code>
 */
class BatchGetDestinationsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Destinations requested.
     *
     * Generated from protobuf field <code>repeated .salto.nebula.destination.v1.Destination destinations = 1;</code>
     */
    private $destinations;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Saltoapis\Nebula\Destination\V1\Destination>|\Google\Protobuf\Internal\RepeatedField $destinations
     *           Destinations requested.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Saltoapis\Nebula\Destination\V1\Destination::initOnce();
        parent::__construct($data);
    }

    /**
     * Destinations requested.
     *
     * Generated from protobuf field <code>repeated .salto.nebula.destination.v1.Destination destinations = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDestinations()
    {
        return $this->destinations;
    }

    /**
     * Destinations requested.
     *
     * Generated from protobuf field <code>repeated .salto.nebula.destination.v1.Destination destinations = 1;</code>
     * @param array<\Saltoapis\Nebula\Destination\V1\Destination>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDestinations($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Saltoapis\Nebula\Destination\V1\Destination::class);
        $this->destinations = $arr;

        return $this;
    }

}

