<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: salto/nebula/accesspointgroup/v1/access_point_group.proto

namespace Saltoapis\Nebula\AccessPointGroup\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The access point group object
 *
 * Generated from protobuf message <code>salto.nebula.accesspointgroup.v1.AccessPointGroup</code>
 */
class AccessPointGroup extends \Google\Protobuf\Internal\Message
{
    /**
     *  Resource name of the access point group. It must have the format of
     * `installations/{@*}access-point-groups/*`. For example:
     * `installations/surelock-homes-hq/access-point-groups/common-accesses`.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Display name of the access point group.
     *
     * Generated from protobuf field <code>string display_name = 3;</code>
     */
    protected $display_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *            Resource name of the access point group. It must have the format of
     *           `installations/{@*}access-point-groups/*`. For example:
     *           `installations/surelock-homes-hq/access-point-groups/common-accesses`.
     *     @type string $display_name
     *           Display name of the access point group.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Saltoapis\Nebula\AccessPointGroup\V1\AccessPointGroup::initOnce();
        parent::__construct($data);
    }

    /**
     *  Resource name of the access point group. It must have the format of
     * `installations/{@*}access-point-groups/*`. For example:
     * `installations/surelock-homes-hq/access-point-groups/common-accesses`.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     *  Resource name of the access point group. It must have the format of
     * `installations/{@*}access-point-groups/*`. For example:
     * `installations/surelock-homes-hq/access-point-groups/common-accesses`.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Display name of the access point group.
     *
     * Generated from protobuf field <code>string display_name = 3;</code>
     * @return string
     */
    public function getDisplayName()
    {
        return $this->display_name;
    }

    /**
     * Display name of the access point group.
     *
     * Generated from protobuf field <code>string display_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDisplayName($var)
    {
        GPBUtil::checkString($var, True);
        $this->display_name = $var;

        return $this;
    }

}

