<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: salto/nebula/file/v1/file.proto

namespace GPBMetadata\Saltoapis\Nebula\File\V1;

class File
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
»
salto/nebula/file/v1/file.protosalto.nebula.file.v1"(
File
name (	

upload_uri (	"#
CreateFileRequest
parent (	2`
FileServiceQ

CreateFile\'.salto.nebula.file.v1.CreateFileRequest.salto.nebula.file.v1.FileBÈ
com.saltoapis.nebula.file.v1B	FileProtoPZ>github.com/saltoapis-internal/saltoapis-go/nebula/file/v1;fileªSaltoapis.Nebula.File.V1ÊSaltoapis\\Nebula\\File\\V1â$GPBMetadata\\Saltoapis\\Nebula\\File\\V1bproto3'
        , true);

        static::$is_initialized = true;
    }
}

