<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: salto/nebula/calendar/v1/calendar.proto

namespace Saltoapis\Nebula\Calendar\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The response message for [`ListCalendars`][salto.nebula.calendar.v1.CalendarService.ListCalendars]
 *
 * Generated from protobuf message <code>salto.nebula.calendar.v1.ListCalendarsResponse</code>
 */
class ListCalendarsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The field name should match the noun `calendars` in the method name.
     * There will be a maximum number of items returned based on the `page_size`
     * field in the request.
     *
     * Generated from protobuf field <code>repeated .salto.nebula.calendar.v1.Calendar calendars = 1;</code>
     */
    private $calendars;
    /**
     * Token to retrieve the next page of results, or empty if there are no more
     * results in the list.
     *
     * Generated from protobuf field <code>string next_page_token = 2;</code>
     */
    protected $next_page_token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Saltoapis\Nebula\Calendar\V1\Calendar>|\Google\Protobuf\Internal\RepeatedField $calendars
     *           The field name should match the noun `calendars` in the method name.
     *           There will be a maximum number of items returned based on the `page_size`
     *           field in the request.
     *     @type string $next_page_token
     *           Token to retrieve the next page of results, or empty if there are no more
     *           results in the list.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Saltoapis\Nebula\Calendar\V1\Calendar::initOnce();
        parent::__construct($data);
    }

    /**
     * The field name should match the noun `calendars` in the method name.
     * There will be a maximum number of items returned based on the `page_size`
     * field in the request.
     *
     * Generated from protobuf field <code>repeated .salto.nebula.calendar.v1.Calendar calendars = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCalendars()
    {
        return $this->calendars;
    }

    /**
     * The field name should match the noun `calendars` in the method name.
     * There will be a maximum number of items returned based on the `page_size`
     * field in the request.
     *
     * Generated from protobuf field <code>repeated .salto.nebula.calendar.v1.Calendar calendars = 1;</code>
     * @param array<\Saltoapis\Nebula\Calendar\V1\Calendar>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCalendars($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Saltoapis\Nebula\Calendar\V1\Calendar::class);
        $this->calendars = $arr;

        return $this;
    }

    /**
     * Token to retrieve the next page of results, or empty if there are no more
     * results in the list.
     *
     * Generated from protobuf field <code>string next_page_token = 2;</code>
     * @return string
     */
    public function getNextPageToken()
    {
        return $this->next_page_token;
    }

    /**
     * Token to retrieve the next page of results, or empty if there are no more
     * results in the list.
     *
     * Generated from protobuf field <code>string next_page_token = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNextPageToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->next_page_token = $var;

        return $this;
    }

}

