<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: salto/nebula/installation/v1/installation.proto

namespace Saltoapis\Nebula\Installation\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Billing info object, belonging to a subscription
 *
 * Generated from protobuf message <code>salto.nebula.installation.v1.BillingInfo</code>
 */
class BillingInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Resource name of the subscription's billing info. It must have the format of
     * `installations/{@*}subscription/billing-info`. For example:
     * `installations/surelock-homes-hq/subscription/billing-info`.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * The company name.
     *
     * Generated from protobuf field <code>string company = 2;</code>
     */
    protected $company = '';
    /**
     * The lines of the address. The first line may include the street name,
     * number, P.O. box, and further lines can include information such as
     * an apartment number, suite or unit.
     *
     * Generated from protobuf field <code>repeated string address = 3;</code>
     */
    private $address;
    /**
     * The region, country or territory code. Must be in ISO 3166-1 format.
     *
     * Generated from protobuf field <code>string region_code = 4;</code>
     */
    protected $region_code = '';
    /**
     * The city, district, suburb, town, or village name.
     *
     * Generated from protobuf field <code>string city = 5;</code>
     */
    protected $city = '';
    /**
     * The state or province code. Must be in ISO 3166-2 format.
     * Mandatory for the following countries: USA, Canada and India.
     * For the rest of the countries, it will be ignored.
     *
     * Generated from protobuf field <code>optional string state_code = 6;</code>
     */
    protected $state_code = null;
    /**
     * The ZIP or postal code.
     *
     * Generated from protobuf field <code>string zip = 7;</code>
     */
    protected $zip = '';
    /**
     * The VAT or Tax Registration Number (TRN).
     *
     * Generated from protobuf field <code>optional string vat_number = 8;</code>
     */
    protected $vat_number = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           Resource name of the subscription's billing info. It must have the format of
     *           `installations/{@*}subscription/billing-info`. For example:
     *           `installations/surelock-homes-hq/subscription/billing-info`.
     *     @type string $company
     *           The company name.
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $address
     *           The lines of the address. The first line may include the street name,
     *           number, P.O. box, and further lines can include information such as
     *           an apartment number, suite or unit.
     *     @type string $region_code
     *           The region, country or territory code. Must be in ISO 3166-1 format.
     *     @type string $city
     *           The city, district, suburb, town, or village name.
     *     @type string $state_code
     *           The state or province code. Must be in ISO 3166-2 format.
     *           Mandatory for the following countries: USA, Canada and India.
     *           For the rest of the countries, it will be ignored.
     *     @type string $zip
     *           The ZIP or postal code.
     *     @type string $vat_number
     *           The VAT or Tax Registration Number (TRN).
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Saltoapis\Nebula\Installation\V1\Installation::initOnce();
        parent::__construct($data);
    }

    /**
     * Resource name of the subscription's billing info. It must have the format of
     * `installations/{@*}subscription/billing-info`. For example:
     * `installations/surelock-homes-hq/subscription/billing-info`.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Resource name of the subscription's billing info. It must have the format of
     * `installations/{@*}subscription/billing-info`. For example:
     * `installations/surelock-homes-hq/subscription/billing-info`.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * The company name.
     *
     * Generated from protobuf field <code>string company = 2;</code>
     * @return string
     */
    public function getCompany()
    {
        return $this->company;
    }

    /**
     * The company name.
     *
     * Generated from protobuf field <code>string company = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCompany($var)
    {
        GPBUtil::checkString($var, True);
        $this->company = $var;

        return $this;
    }

    /**
     * The lines of the address. The first line may include the street name,
     * number, P.O. box, and further lines can include information such as
     * an apartment number, suite or unit.
     *
     * Generated from protobuf field <code>repeated string address = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * The lines of the address. The first line may include the street name,
     * number, P.O. box, and further lines can include information such as
     * an apartment number, suite or unit.
     *
     * Generated from protobuf field <code>repeated string address = 3;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAddress($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->address = $arr;

        return $this;
    }

    /**
     * The region, country or territory code. Must be in ISO 3166-1 format.
     *
     * Generated from protobuf field <code>string region_code = 4;</code>
     * @return string
     */
    public function getRegionCode()
    {
        return $this->region_code;
    }

    /**
     * The region, country or territory code. Must be in ISO 3166-1 format.
     *
     * Generated from protobuf field <code>string region_code = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setRegionCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->region_code = $var;

        return $this;
    }

    /**
     * The city, district, suburb, town, or village name.
     *
     * Generated from protobuf field <code>string city = 5;</code>
     * @return string
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * The city, district, suburb, town, or village name.
     *
     * Generated from protobuf field <code>string city = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setCity($var)
    {
        GPBUtil::checkString($var, True);
        $this->city = $var;

        return $this;
    }

    /**
     * The state or province code. Must be in ISO 3166-2 format.
     * Mandatory for the following countries: USA, Canada and India.
     * For the rest of the countries, it will be ignored.
     *
     * Generated from protobuf field <code>optional string state_code = 6;</code>
     * @return string
     */
    public function getStateCode()
    {
        return isset($this->state_code) ? $this->state_code : '';
    }

    public function hasStateCode()
    {
        return isset($this->state_code);
    }

    public function clearStateCode()
    {
        unset($this->state_code);
    }

    /**
     * The state or province code. Must be in ISO 3166-2 format.
     * Mandatory for the following countries: USA, Canada and India.
     * For the rest of the countries, it will be ignored.
     *
     * Generated from protobuf field <code>optional string state_code = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setStateCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->state_code = $var;

        return $this;
    }

    /**
     * The ZIP or postal code.
     *
     * Generated from protobuf field <code>string zip = 7;</code>
     * @return string
     */
    public function getZip()
    {
        return $this->zip;
    }

    /**
     * The ZIP or postal code.
     *
     * Generated from protobuf field <code>string zip = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setZip($var)
    {
        GPBUtil::checkString($var, True);
        $this->zip = $var;

        return $this;
    }

    /**
     * The VAT or Tax Registration Number (TRN).
     *
     * Generated from protobuf field <code>optional string vat_number = 8;</code>
     * @return string
     */
    public function getVatNumber()
    {
        return isset($this->vat_number) ? $this->vat_number : '';
    }

    public function hasVatNumber()
    {
        return isset($this->vat_number);
    }

    public function clearVatNumber()
    {
        unset($this->vat_number);
    }

    /**
     * The VAT or Tax Registration Number (TRN).
     *
     * Generated from protobuf field <code>optional string vat_number = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setVatNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->vat_number = $var;

        return $this;
    }

}

