<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: salto/nebula/installation/v1/installation.proto

namespace Saltoapis\Nebula\Installation\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The request message for [`CreatePaymentAuthorization`][salto.nebula.installation.v1.InstallationService.CreatePaymentAuthorization]
 *
 * Generated from protobuf message <code>salto.nebula.installation.v1.CreatePaymentAuthorizationRequest</code>
 */
class CreatePaymentAuthorizationRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The resource name of the subscription for which the payment authorization is being
     * requested to be created. For example:
     * `installations/surelock-homes-hq/subscription`.
     *
     * Generated from protobuf field <code>string parent = 1;</code>
     */
    protected $parent = '';
    /**
     * The payment authorization resource to be created. Client must not set the
     * `PaymentAuthorization.name` field.
     *
     * Generated from protobuf field <code>.salto.nebula.installation.v1.PaymentAuthorization payment_authorization = 2;</code>
     */
    protected $payment_authorization = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $parent
     *           The resource name of the subscription for which the payment authorization is being
     *           requested to be created. For example:
     *           `installations/surelock-homes-hq/subscription`.
     *     @type \Saltoapis\Nebula\Installation\V1\PaymentAuthorization $payment_authorization
     *           The payment authorization resource to be created. Client must not set the
     *           `PaymentAuthorization.name` field.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Saltoapis\Nebula\Installation\V1\Installation::initOnce();
        parent::__construct($data);
    }

    /**
     * The resource name of the subscription for which the payment authorization is being
     * requested to be created. For example:
     * `installations/surelock-homes-hq/subscription`.
     *
     * Generated from protobuf field <code>string parent = 1;</code>
     * @return string
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * The resource name of the subscription for which the payment authorization is being
     * requested to be created. For example:
     * `installations/surelock-homes-hq/subscription`.
     *
     * Generated from protobuf field <code>string parent = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setParent($var)
    {
        GPBUtil::checkString($var, True);
        $this->parent = $var;

        return $this;
    }

    /**
     * The payment authorization resource to be created. Client must not set the
     * `PaymentAuthorization.name` field.
     *
     * Generated from protobuf field <code>.salto.nebula.installation.v1.PaymentAuthorization payment_authorization = 2;</code>
     * @return \Saltoapis\Nebula\Installation\V1\PaymentAuthorization|null
     */
    public function getPaymentAuthorization()
    {
        return $this->payment_authorization;
    }

    public function hasPaymentAuthorization()
    {
        return isset($this->payment_authorization);
    }

    public function clearPaymentAuthorization()
    {
        unset($this->payment_authorization);
    }

    /**
     * The payment authorization resource to be created. Client must not set the
     * `PaymentAuthorization.name` field.
     *
     * Generated from protobuf field <code>.salto.nebula.installation.v1.PaymentAuthorization payment_authorization = 2;</code>
     * @param \Saltoapis\Nebula\Installation\V1\PaymentAuthorization $var
     * @return $this
     */
    public function setPaymentAuthorization($var)
    {
        GPBUtil::checkMessage($var, \Saltoapis\Nebula\Installation\V1\PaymentAuthorization::class);
        $this->payment_authorization = $var;

        return $this;
    }

}

