<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: salto/nebula/installation/v1/installation.proto

namespace Saltoapis\Nebula\Installation\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The request message for [`CreateInstallation`][salto.nebula.installation.v1.InstallationService.CreateInstallation]
 *
 * Generated from protobuf message <code>salto.nebula.installation.v1.CreateInstallationRequest</code>
 */
class CreateInstallationRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The installation ID to use for this installation. In case it's
     * empty the server will autogenerate a unique identifier.
     *
     * Generated from protobuf field <code>optional string installation_id = 1;</code>
     */
    protected $installation_id = null;
    /**
     * The installation resource to be created. Client must not set the
     * `Installation.name` field.
     *
     * Generated from protobuf field <code>.salto.nebula.installation.v1.Installation installation = 2;</code>
     */
    protected $installation = null;
    /**
     * If set, validate the request but do not actually create the installation.
     *
     * Generated from protobuf field <code>optional bool validate_only = 5;</code>
     */
    protected $validate_only = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $installation_id
     *           The installation ID to use for this installation. In case it's
     *           empty the server will autogenerate a unique identifier.
     *     @type \Saltoapis\Nebula\Installation\V1\Installation $installation
     *           The installation resource to be created. Client must not set the
     *           `Installation.name` field.
     *     @type bool $validate_only
     *           If set, validate the request but do not actually create the installation.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Saltoapis\Nebula\Installation\V1\Installation::initOnce();
        parent::__construct($data);
    }

    /**
     * The installation ID to use for this installation. In case it's
     * empty the server will autogenerate a unique identifier.
     *
     * Generated from protobuf field <code>optional string installation_id = 1;</code>
     * @return string
     */
    public function getInstallationId()
    {
        return isset($this->installation_id) ? $this->installation_id : '';
    }

    public function hasInstallationId()
    {
        return isset($this->installation_id);
    }

    public function clearInstallationId()
    {
        unset($this->installation_id);
    }

    /**
     * The installation ID to use for this installation. In case it's
     * empty the server will autogenerate a unique identifier.
     *
     * Generated from protobuf field <code>optional string installation_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setInstallationId($var)
    {
        GPBUtil::checkString($var, True);
        $this->installation_id = $var;

        return $this;
    }

    /**
     * The installation resource to be created. Client must not set the
     * `Installation.name` field.
     *
     * Generated from protobuf field <code>.salto.nebula.installation.v1.Installation installation = 2;</code>
     * @return \Saltoapis\Nebula\Installation\V1\Installation|null
     */
    public function getInstallation()
    {
        return $this->installation;
    }

    public function hasInstallation()
    {
        return isset($this->installation);
    }

    public function clearInstallation()
    {
        unset($this->installation);
    }

    /**
     * The installation resource to be created. Client must not set the
     * `Installation.name` field.
     *
     * Generated from protobuf field <code>.salto.nebula.installation.v1.Installation installation = 2;</code>
     * @param \Saltoapis\Nebula\Installation\V1\Installation $var
     * @return $this
     */
    public function setInstallation($var)
    {
        GPBUtil::checkMessage($var, \Saltoapis\Nebula\Installation\V1\Installation::class);
        $this->installation = $var;

        return $this;
    }

    /**
     * If set, validate the request but do not actually create the installation.
     *
     * Generated from protobuf field <code>optional bool validate_only = 5;</code>
     * @return bool
     */
    public function getValidateOnly()
    {
        return isset($this->validate_only) ? $this->validate_only : false;
    }

    public function hasValidateOnly()
    {
        return isset($this->validate_only);
    }

    public function clearValidateOnly()
    {
        unset($this->validate_only);
    }

    /**
     * If set, validate the request but do not actually create the installation.
     *
     * Generated from protobuf field <code>optional bool validate_only = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setValidateOnly($var)
    {
        GPBUtil::checkBool($var);
        $this->validate_only = $var;

        return $this;
    }

}

