<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: salto/nebula/installation/v1/installation.proto

namespace Saltoapis\Nebula\Installation\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The request message for [`CreatePolicy`][salto.nebula.installation.v1.InstallationService.CreatePolicy]
 *
 * Generated from protobuf message <code>salto.nebula.installation.v1.CreatePolicyRequest</code>
 */
class CreatePolicyRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Resource name of the parent resource where to create the IAM policy. For
     * example: `installations/salto-hq`.
     *
     * Generated from protobuf field <code>string parent = 1;</code>
     */
    protected $parent = '';
    /**
     * The policy ID to use for the IAM policy. In case it's empty the server
     * will autogenerate a unique identifier.
     *
     * Generated from protobuf field <code>string policy_id = 2;</code>
     */
    protected $policy_id = '';
    /**
     * The policy resource to be created. Client must not set the `Policy.name`
     * field.
     *
     * Generated from protobuf field <code>.salto.nebula.installation.v1.Policy policy = 3;</code>
     */
    protected $policy = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $parent
     *           Resource name of the parent resource where to create the IAM policy. For
     *           example: `installations/salto-hq`.
     *     @type string $policy_id
     *           The policy ID to use for the IAM policy. In case it's empty the server
     *           will autogenerate a unique identifier.
     *     @type \Saltoapis\Nebula\Installation\V1\Policy $policy
     *           The policy resource to be created. Client must not set the `Policy.name`
     *           field.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Saltoapis\Nebula\Installation\V1\Installation::initOnce();
        parent::__construct($data);
    }

    /**
     * Resource name of the parent resource where to create the IAM policy. For
     * example: `installations/salto-hq`.
     *
     * Generated from protobuf field <code>string parent = 1;</code>
     * @return string
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * Resource name of the parent resource where to create the IAM policy. For
     * example: `installations/salto-hq`.
     *
     * Generated from protobuf field <code>string parent = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setParent($var)
    {
        GPBUtil::checkString($var, True);
        $this->parent = $var;

        return $this;
    }

    /**
     * The policy ID to use for the IAM policy. In case it's empty the server
     * will autogenerate a unique identifier.
     *
     * Generated from protobuf field <code>string policy_id = 2;</code>
     * @return string
     */
    public function getPolicyId()
    {
        return $this->policy_id;
    }

    /**
     * The policy ID to use for the IAM policy. In case it's empty the server
     * will autogenerate a unique identifier.
     *
     * Generated from protobuf field <code>string policy_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPolicyId($var)
    {
        GPBUtil::checkString($var, True);
        $this->policy_id = $var;

        return $this;
    }

    /**
     * The policy resource to be created. Client must not set the `Policy.name`
     * field.
     *
     * Generated from protobuf field <code>.salto.nebula.installation.v1.Policy policy = 3;</code>
     * @return \Saltoapis\Nebula\Installation\V1\Policy|null
     */
    public function getPolicy()
    {
        return $this->policy;
    }

    public function hasPolicy()
    {
        return isset($this->policy);
    }

    public function clearPolicy()
    {
        unset($this->policy);
    }

    /**
     * The policy resource to be created. Client must not set the `Policy.name`
     * field.
     *
     * Generated from protobuf field <code>.salto.nebula.installation.v1.Policy policy = 3;</code>
     * @param \Saltoapis\Nebula\Installation\V1\Policy $var
     * @return $this
     */
    public function setPolicy($var)
    {
        GPBUtil::checkMessage($var, \Saltoapis\Nebula\Installation\V1\Policy::class);
        $this->policy = $var;

        return $this;
    }

}

