<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: salto/nebula/installation/v1/installation.proto

namespace Saltoapis\Nebula\Installation\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The invoice object used for billing
 *
 * Generated from protobuf message <code>salto.nebula.installation.v1.Invoice</code>
 */
class Invoice extends \Google\Protobuf\Internal\Message
{
    /**
     * Resource name of the invoice. It must have the format of
     * `installations/{@*}subscription/invoices/*`. For example:
     * `installations/salto-hq/subscription/invoices/2023-000015`.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Start time of the invoice. It must be past time.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp start_time = 2;</code>
     */
    protected $start_time = null;
    /**
     * End time of the invoice.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp end_time = 3;</code>
     */
    protected $end_time = null;
    /**
     * The line items included in the invoice. Must include at least one
     * item and no more than 50.
     *
     * Generated from protobuf field <code>repeated .salto.nebula.installation.v1.Invoice.LineItem line_items = 4;</code>
     */
    private $line_items;
    /**
     * The total cost of the invoice.
     * The value is in the minor unit of the currency. (for example: cents).
     *
     * Generated from protobuf field <code>int64 total = 5;</code>
     */
    protected $total = 0;
    /**
     * Indicates whether this invoice has been paid or not.
     *
     * Generated from protobuf field <code>.salto.nebula.installation.v1.Invoice.State state = 6;</code>
     */
    protected $state = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           Resource name of the invoice. It must have the format of
     *           `installations/{@*}subscription/invoices/*`. For example:
     *           `installations/salto-hq/subscription/invoices/2023-000015`.
     *     @type \Google\Protobuf\Timestamp $start_time
     *           Start time of the invoice. It must be past time.
     *     @type \Google\Protobuf\Timestamp $end_time
     *           End time of the invoice.
     *     @type array<\Saltoapis\Nebula\Installation\V1\Invoice\LineItem>|\Google\Protobuf\Internal\RepeatedField $line_items
     *           The line items included in the invoice. Must include at least one
     *           item and no more than 50.
     *     @type int|string $total
     *           The total cost of the invoice.
     *           The value is in the minor unit of the currency. (for example: cents).
     *     @type int $state
     *           Indicates whether this invoice has been paid or not.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Saltoapis\Nebula\Installation\V1\Installation::initOnce();
        parent::__construct($data);
    }

    /**
     * Resource name of the invoice. It must have the format of
     * `installations/{@*}subscription/invoices/*`. For example:
     * `installations/salto-hq/subscription/invoices/2023-000015`.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Resource name of the invoice. It must have the format of
     * `installations/{@*}subscription/invoices/*`. For example:
     * `installations/salto-hq/subscription/invoices/2023-000015`.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Start time of the invoice. It must be past time.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp start_time = 2;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getStartTime()
    {
        return $this->start_time;
    }

    public function hasStartTime()
    {
        return isset($this->start_time);
    }

    public function clearStartTime()
    {
        unset($this->start_time);
    }

    /**
     * Start time of the invoice. It must be past time.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp start_time = 2;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setStartTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->start_time = $var;

        return $this;
    }

    /**
     * End time of the invoice.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp end_time = 3;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getEndTime()
    {
        return $this->end_time;
    }

    public function hasEndTime()
    {
        return isset($this->end_time);
    }

    public function clearEndTime()
    {
        unset($this->end_time);
    }

    /**
     * End time of the invoice.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp end_time = 3;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setEndTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->end_time = $var;

        return $this;
    }

    /**
     * The line items included in the invoice. Must include at least one
     * item and no more than 50.
     *
     * Generated from protobuf field <code>repeated .salto.nebula.installation.v1.Invoice.LineItem line_items = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLineItems()
    {
        return $this->line_items;
    }

    /**
     * The line items included in the invoice. Must include at least one
     * item and no more than 50.
     *
     * Generated from protobuf field <code>repeated .salto.nebula.installation.v1.Invoice.LineItem line_items = 4;</code>
     * @param array<\Saltoapis\Nebula\Installation\V1\Invoice\LineItem>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLineItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Saltoapis\Nebula\Installation\V1\Invoice\LineItem::class);
        $this->line_items = $arr;

        return $this;
    }

    /**
     * The total cost of the invoice.
     * The value is in the minor unit of the currency. (for example: cents).
     *
     * Generated from protobuf field <code>int64 total = 5;</code>
     * @return int|string
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     * The total cost of the invoice.
     * The value is in the minor unit of the currency. (for example: cents).
     *
     * Generated from protobuf field <code>int64 total = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotal($var)
    {
        GPBUtil::checkInt64($var);
        $this->total = $var;

        return $this;
    }

    /**
     * Indicates whether this invoice has been paid or not.
     *
     * Generated from protobuf field <code>.salto.nebula.installation.v1.Invoice.State state = 6;</code>
     * @return int
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * Indicates whether this invoice has been paid or not.
     *
     * Generated from protobuf field <code>.salto.nebula.installation.v1.Invoice.State state = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setState($var)
    {
        GPBUtil::checkEnum($var, \Saltoapis\Nebula\Installation\V1\Invoice\State::class);
        $this->state = $var;

        return $this;
    }

}

