<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: salto/nebula/installation/v1/installation.proto

namespace Saltoapis\Nebula\Installation\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The request message for [`UpdateInstallation`][salto.nebula.installation.v1.InstallationService.UpdateInstallation]
 *
 * Generated from protobuf message <code>salto.nebula.installation.v1.UpdateInstallationRequest</code>
 */
class UpdateInstallationRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The installation resource which replaces the resource on the server.
     *
     * Generated from protobuf field <code>.salto.nebula.installation.v1.Installation installation = 1;</code>
     */
    protected $installation = null;
    /**
     * The update mask applied to the resource.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask update_mask = 2;</code>
     */
    protected $update_mask = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Saltoapis\Nebula\Installation\V1\Installation $installation
     *           The installation resource which replaces the resource on the server.
     *     @type \Google\Protobuf\FieldMask $update_mask
     *           The update mask applied to the resource.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Saltoapis\Nebula\Installation\V1\Installation::initOnce();
        parent::__construct($data);
    }

    /**
     * The installation resource which replaces the resource on the server.
     *
     * Generated from protobuf field <code>.salto.nebula.installation.v1.Installation installation = 1;</code>
     * @return \Saltoapis\Nebula\Installation\V1\Installation|null
     */
    public function getInstallation()
    {
        return $this->installation;
    }

    public function hasInstallation()
    {
        return isset($this->installation);
    }

    public function clearInstallation()
    {
        unset($this->installation);
    }

    /**
     * The installation resource which replaces the resource on the server.
     *
     * Generated from protobuf field <code>.salto.nebula.installation.v1.Installation installation = 1;</code>
     * @param \Saltoapis\Nebula\Installation\V1\Installation $var
     * @return $this
     */
    public function setInstallation($var)
    {
        GPBUtil::checkMessage($var, \Saltoapis\Nebula\Installation\V1\Installation::class);
        $this->installation = $var;

        return $this;
    }

    /**
     * The update mask applied to the resource.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask update_mask = 2;</code>
     * @return \Google\Protobuf\FieldMask|null
     */
    public function getUpdateMask()
    {
        return $this->update_mask;
    }

    public function hasUpdateMask()
    {
        return isset($this->update_mask);
    }

    public function clearUpdateMask()
    {
        unset($this->update_mask);
    }

    /**
     * The update mask applied to the resource.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask update_mask = 2;</code>
     * @param \Google\Protobuf\FieldMask $var
     * @return $this
     */
    public function setUpdateMask($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\FieldMask::class);
        $this->update_mask = $var;

        return $this;
    }

}

