<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: salto/nebula/installation/v1/installation.proto

namespace Saltoapis\Nebula\Installation\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * (-- api-linter: core::0134::request-mask-required=disabled
 *     aip.dev/not-precedent: We need to do this to simplify the update operation. --)
 * The request message for [`UpdatePaymentMethod`][salto.nebula.installation.v1.InstallationService.UpdatePaymentMethod]
 *
 * Generated from protobuf message <code>salto.nebula.installation.v1.UpdatePaymentMethodRequest</code>
 */
class UpdatePaymentMethodRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The payment method resource which replaces the resource on the server.
     *
     * Generated from protobuf field <code>.salto.nebula.installation.v1.PaymentMethod payment_method = 1;</code>
     */
    protected $payment_method = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Saltoapis\Nebula\Installation\V1\PaymentMethod $payment_method
     *           The payment method resource which replaces the resource on the server.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Saltoapis\Nebula\Installation\V1\Installation::initOnce();
        parent::__construct($data);
    }

    /**
     * The payment method resource which replaces the resource on the server.
     *
     * Generated from protobuf field <code>.salto.nebula.installation.v1.PaymentMethod payment_method = 1;</code>
     * @return \Saltoapis\Nebula\Installation\V1\PaymentMethod|null
     */
    public function getPaymentMethod()
    {
        return $this->payment_method;
    }

    public function hasPaymentMethod()
    {
        return isset($this->payment_method);
    }

    public function clearPaymentMethod()
    {
        unset($this->payment_method);
    }

    /**
     * The payment method resource which replaces the resource on the server.
     *
     * Generated from protobuf field <code>.salto.nebula.installation.v1.PaymentMethod payment_method = 1;</code>
     * @param \Saltoapis\Nebula\Installation\V1\PaymentMethod $var
     * @return $this
     */
    public function setPaymentMethod($var)
    {
        GPBUtil::checkMessage($var, \Saltoapis\Nebula\Installation\V1\PaymentMethod::class);
        $this->payment_method = $var;

        return $this;
    }

}

