<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: salto/nebula/booking/v1/booking.proto

namespace Saltoapis\Nebula\Booking\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * The booking object
 * Represents a booking resource that contains the contractual details of a stay,
 * decoupled from the physical state of the booked asset.
 *
 * Generated from protobuf message <code>salto.nebula.booking.v1.Booking</code>
 */
class Booking extends \Google\Protobuf\Internal\Message
{
    /**
     * Output only. Resource name of the booking. It must have the format of
     * `installations/{@*}bookings/*`. For example:
     * `installations/surelock-homes-hq/bookings/my-booking`.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * The start time of the booking. When creating a booking, this is the planned
     * start time. Once the booking has started/checked in, it represents the
     * actual start time.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp start_time = 2;</code>
     */
    protected $start_time = null;
    /**
     * The end time of the booking. When creating a booking, this is the planned
     * end time. Once the booking has completed/checked out, it represents the
     * actual end time.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp end_time = 3;</code>
     */
    protected $end_time = null;
    /**
     * The lifecycle state of the booking.
     *
     * Generated from protobuf field <code>.salto.nebula.booking.v1.Booking.State state = 4;</code>
     */
    protected $state = 0;
    /**
     * The timestamp when the check-in was performed.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp check_in_time = 5;</code>
     */
    protected $check_in_time = null;
    /**
     * The timestamp when the check-out was performed.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp check_out_time = 6;</code>
     */
    protected $check_out_time = null;
    /**
     * Access rights explicitly associated with the booking, such as common areas
     * or facilities. A maximum of 5 access rights can be specified.
     * These access rights are combined with the default access rights provided by
     * the booked asset. They ensure the user has access to necessary areas as
     * part of this booking, regardless of the specific asset's configuration.
     *
     * Generated from protobuf field <code>repeated string access_rights = 8;</code>
     */
    private $access_rights;
    protected $asset;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           Output only. Resource name of the booking. It must have the format of
     *           `installations/{@*}bookings/*`. For example:
     *           `installations/surelock-homes-hq/bookings/my-booking`.
     *     @type \Google\Protobuf\Timestamp $start_time
     *           The start time of the booking. When creating a booking, this is the planned
     *           start time. Once the booking has started/checked in, it represents the
     *           actual start time.
     *     @type \Google\Protobuf\Timestamp $end_time
     *           The end time of the booking. When creating a booking, this is the planned
     *           end time. Once the booking has completed/checked out, it represents the
     *           actual end time.
     *     @type int $state
     *           The lifecycle state of the booking.
     *     @type \Google\Protobuf\Timestamp $check_in_time
     *           The timestamp when the check-in was performed.
     *     @type \Google\Protobuf\Timestamp $check_out_time
     *           The timestamp when the check-out was performed.
     *     @type string $unit
     *           The unit resource reference assigned to the booking.
     *     @type string[] $access_rights
     *           Access rights explicitly associated with the booking, such as common areas
     *           or facilities. A maximum of 5 access rights can be specified.
     *           These access rights are combined with the default access rights provided by
     *           the booked asset. They ensure the user has access to necessary areas as
     *           part of this booking, regardless of the specific asset's configuration.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Saltoapis\Nebula\Booking\V1\Booking::initOnce();
        parent::__construct($data);
    }

    /**
     * Output only. Resource name of the booking. It must have the format of
     * `installations/{@*}bookings/*`. For example:
     * `installations/surelock-homes-hq/bookings/my-booking`.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Output only. Resource name of the booking. It must have the format of
     * `installations/{@*}bookings/*`. For example:
     * `installations/surelock-homes-hq/bookings/my-booking`.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * The start time of the booking. When creating a booking, this is the planned
     * start time. Once the booking has started/checked in, it represents the
     * actual start time.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp start_time = 2;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getStartTime()
    {
        return $this->start_time;
    }

    public function hasStartTime()
    {
        return isset($this->start_time);
    }

    public function clearStartTime()
    {
        unset($this->start_time);
    }

    /**
     * The start time of the booking. When creating a booking, this is the planned
     * start time. Once the booking has started/checked in, it represents the
     * actual start time.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp start_time = 2;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setStartTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->start_time = $var;

        return $this;
    }

    /**
     * The end time of the booking. When creating a booking, this is the planned
     * end time. Once the booking has completed/checked out, it represents the
     * actual end time.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp end_time = 3;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getEndTime()
    {
        return $this->end_time;
    }

    public function hasEndTime()
    {
        return isset($this->end_time);
    }

    public function clearEndTime()
    {
        unset($this->end_time);
    }

    /**
     * The end time of the booking. When creating a booking, this is the planned
     * end time. Once the booking has completed/checked out, it represents the
     * actual end time.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp end_time = 3;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setEndTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->end_time = $var;

        return $this;
    }

    /**
     * The lifecycle state of the booking.
     *
     * Generated from protobuf field <code>.salto.nebula.booking.v1.Booking.State state = 4;</code>
     * @return int
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * The lifecycle state of the booking.
     *
     * Generated from protobuf field <code>.salto.nebula.booking.v1.Booking.State state = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setState($var)
    {
        GPBUtil::checkEnum($var, \Saltoapis\Nebula\Booking\V1\Booking\State::class);
        $this->state = $var;

        return $this;
    }

    /**
     * The timestamp when the check-in was performed.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp check_in_time = 5;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getCheckInTime()
    {
        return $this->check_in_time;
    }

    public function hasCheckInTime()
    {
        return isset($this->check_in_time);
    }

    public function clearCheckInTime()
    {
        unset($this->check_in_time);
    }

    /**
     * The timestamp when the check-in was performed.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp check_in_time = 5;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setCheckInTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->check_in_time = $var;

        return $this;
    }

    /**
     * The timestamp when the check-out was performed.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp check_out_time = 6;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getCheckOutTime()
    {
        return $this->check_out_time;
    }

    public function hasCheckOutTime()
    {
        return isset($this->check_out_time);
    }

    public function clearCheckOutTime()
    {
        unset($this->check_out_time);
    }

    /**
     * The timestamp when the check-out was performed.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp check_out_time = 6;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setCheckOutTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->check_out_time = $var;

        return $this;
    }

    /**
     * The unit resource reference assigned to the booking.
     *
     * Generated from protobuf field <code>string unit = 7;</code>
     * @return string
     */
    public function getUnit()
    {
        return $this->readOneof(7);
    }

    public function hasUnit()
    {
        return $this->hasOneof(7);
    }

    /**
     * The unit resource reference assigned to the booking.
     *
     * Generated from protobuf field <code>string unit = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setUnit($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(7, $var);

        return $this;
    }

    /**
     * Access rights explicitly associated with the booking, such as common areas
     * or facilities. A maximum of 5 access rights can be specified.
     * These access rights are combined with the default access rights provided by
     * the booked asset. They ensure the user has access to necessary areas as
     * part of this booking, regardless of the specific asset's configuration.
     *
     * Generated from protobuf field <code>repeated string access_rights = 8;</code>
     * @return RepeatedField<string>
     */
    public function getAccessRights()
    {
        return $this->access_rights;
    }

    /**
     * Access rights explicitly associated with the booking, such as common areas
     * or facilities. A maximum of 5 access rights can be specified.
     * These access rights are combined with the default access rights provided by
     * the booked asset. They ensure the user has access to necessary areas as
     * part of this booking, regardless of the specific asset's configuration.
     *
     * Generated from protobuf field <code>repeated string access_rights = 8;</code>
     * @param string[] $var
     * @return $this
     */
    public function setAccessRights($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->access_rights = $arr;

        return $this;
    }

    /**
     * @return string
     */
    public function getAsset()
    {
        return $this->whichOneof("asset");
    }

}

