<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: salto/nebula/booking/v1/booking.proto

namespace Saltoapis\Nebula\Booking\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * The request message for [CreateBooking][salto.nebula.booking.v1.BookingService.CreateBooking]
 *
 * Generated from protobuf message <code>salto.nebula.booking.v1.CreateBookingRequest</code>
 */
class CreateBookingRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Resource name of the parent resource under which the booking is created. For
     * example: `installations/surelock-homes-hq`.
     *
     * Generated from protobuf field <code>string parent = 1;</code>
     */
    protected $parent = '';
    /**
     * The booking ID to use for this booking. In case it's empty the
     * server will autogenerate a unique identifier.
     *
     * Generated from protobuf field <code>optional string booking_id = 2;</code>
     */
    protected $booking_id = null;
    /**
     * The booking resource to be created. Client must not set the
     * `Booking.name` field.
     *
     * Generated from protobuf field <code>.salto.nebula.booking.v1.Booking booking = 3;</code>
     */
    protected $booking = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $parent
     *           Resource name of the parent resource under which the booking is created. For
     *           example: `installations/surelock-homes-hq`.
     *     @type string $booking_id
     *           The booking ID to use for this booking. In case it's empty the
     *           server will autogenerate a unique identifier.
     *     @type \Saltoapis\Nebula\Booking\V1\Booking $booking
     *           The booking resource to be created. Client must not set the
     *           `Booking.name` field.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Saltoapis\Nebula\Booking\V1\Booking::initOnce();
        parent::__construct($data);
    }

    /**
     * Resource name of the parent resource under which the booking is created. For
     * example: `installations/surelock-homes-hq`.
     *
     * Generated from protobuf field <code>string parent = 1;</code>
     * @return string
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * Resource name of the parent resource under which the booking is created. For
     * example: `installations/surelock-homes-hq`.
     *
     * Generated from protobuf field <code>string parent = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setParent($var)
    {
        GPBUtil::checkString($var, True);
        $this->parent = $var;

        return $this;
    }

    /**
     * The booking ID to use for this booking. In case it's empty the
     * server will autogenerate a unique identifier.
     *
     * Generated from protobuf field <code>optional string booking_id = 2;</code>
     * @return string
     */
    public function getBookingId()
    {
        return isset($this->booking_id) ? $this->booking_id : '';
    }

    public function hasBookingId()
    {
        return isset($this->booking_id);
    }

    public function clearBookingId()
    {
        unset($this->booking_id);
    }

    /**
     * The booking ID to use for this booking. In case it's empty the
     * server will autogenerate a unique identifier.
     *
     * Generated from protobuf field <code>optional string booking_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setBookingId($var)
    {
        GPBUtil::checkString($var, True);
        $this->booking_id = $var;

        return $this;
    }

    /**
     * The booking resource to be created. Client must not set the
     * `Booking.name` field.
     *
     * Generated from protobuf field <code>.salto.nebula.booking.v1.Booking booking = 3;</code>
     * @return \Saltoapis\Nebula\Booking\V1\Booking|null
     */
    public function getBooking()
    {
        return $this->booking;
    }

    public function hasBooking()
    {
        return isset($this->booking);
    }

    public function clearBooking()
    {
        unset($this->booking);
    }

    /**
     * The booking resource to be created. Client must not set the
     * `Booking.name` field.
     *
     * Generated from protobuf field <code>.salto.nebula.booking.v1.Booking booking = 3;</code>
     * @param \Saltoapis\Nebula\Booking\V1\Booking $var
     * @return $this
     */
    public function setBooking($var)
    {
        GPBUtil::checkMessage($var, \Saltoapis\Nebula\Booking\V1\Booking::class);
        $this->booking = $var;

        return $this;
    }

}

