<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: salto/nebula/booking/v1/booking.proto

namespace Saltoapis\Nebula\Booking\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * The response message for [ListBookings][salto.nebula.booking.v1.BookingService.ListBookings]
 *
 * Generated from protobuf message <code>salto.nebula.booking.v1.ListBookingsResponse</code>
 */
class ListBookingsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The field name should match the noun `bookings` in the method name. There
     * will be a maximum number of items returned based on the `page_size` field
     * in the request.
     *
     * Generated from protobuf field <code>repeated .salto.nebula.booking.v1.Booking bookings = 1;</code>
     */
    private $bookings;
    /**
     * Token to retrieve the next page of results, or empty if there are no more
     * results in the list.
     *
     * Generated from protobuf field <code>string next_page_token = 2;</code>
     */
    protected $next_page_token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Saltoapis\Nebula\Booking\V1\Booking[] $bookings
     *           The field name should match the noun `bookings` in the method name. There
     *           will be a maximum number of items returned based on the `page_size` field
     *           in the request.
     *     @type string $next_page_token
     *           Token to retrieve the next page of results, or empty if there are no more
     *           results in the list.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Saltoapis\Nebula\Booking\V1\Booking::initOnce();
        parent::__construct($data);
    }

    /**
     * The field name should match the noun `bookings` in the method name. There
     * will be a maximum number of items returned based on the `page_size` field
     * in the request.
     *
     * Generated from protobuf field <code>repeated .salto.nebula.booking.v1.Booking bookings = 1;</code>
     * @return RepeatedField<\Saltoapis\Nebula\Booking\V1\Booking>
     */
    public function getBookings()
    {
        return $this->bookings;
    }

    /**
     * The field name should match the noun `bookings` in the method name. There
     * will be a maximum number of items returned based on the `page_size` field
     * in the request.
     *
     * Generated from protobuf field <code>repeated .salto.nebula.booking.v1.Booking bookings = 1;</code>
     * @param \Saltoapis\Nebula\Booking\V1\Booking[] $var
     * @return $this
     */
    public function setBookings($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Saltoapis\Nebula\Booking\V1\Booking::class);
        $this->bookings = $arr;

        return $this;
    }

    /**
     * Token to retrieve the next page of results, or empty if there are no more
     * results in the list.
     *
     * Generated from protobuf field <code>string next_page_token = 2;</code>
     * @return string
     */
    public function getNextPageToken()
    {
        return $this->next_page_token;
    }

    /**
     * Token to retrieve the next page of results, or empty if there are no more
     * results in the list.
     *
     * Generated from protobuf field <code>string next_page_token = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNextPageToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->next_page_token = $var;

        return $this;
    }

}

