<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: salto/nebula/accesspoint/v1/access_point.proto

namespace Saltoapis\Nebula\AccessPoint\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The request message for [`CreateAccessPoint`][salto.nebula.accesspoint.v1.AccessPointService.CreateAccessPoint]
 *
 * Generated from protobuf message <code>salto.nebula.accesspoint.v1.CreateAccessPointRequest</code>
 */
class CreateAccessPointRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Resource name of the parent resource under which the access point is created.
     * For example, `installations/surelock-homes-hq`.
     *
     * Generated from protobuf field <code>string parent = 1;</code>
     */
    protected $parent = '';
    /**
     * The access point id to use for this access point. If it's
     * empty the server will autogenerate a unique identifier.
     *
     * Generated from protobuf field <code>optional string access_point_id = 2;</code>
     */
    protected $access_point_id = null;
    /**
     * The access point resource to be created. Client must not set the
     * `AccessPoint.name` field.
     *
     * Generated from protobuf field <code>.salto.nebula.accesspoint.v1.AccessPoint access_point = 3;</code>
     */
    protected $access_point = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $parent
     *           Resource name of the parent resource under which the access point is created.
     *           For example, `installations/surelock-homes-hq`.
     *     @type string $access_point_id
     *           The access point id to use for this access point. If it's
     *           empty the server will autogenerate a unique identifier.
     *     @type \Saltoapis\Nebula\AccessPoint\V1\AccessPoint $access_point
     *           The access point resource to be created. Client must not set the
     *           `AccessPoint.name` field.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Saltoapis\Nebula\AccessPoint\V1\AccessPoint::initOnce();
        parent::__construct($data);
    }

    /**
     * Resource name of the parent resource under which the access point is created.
     * For example, `installations/surelock-homes-hq`.
     *
     * Generated from protobuf field <code>string parent = 1;</code>
     * @return string
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * Resource name of the parent resource under which the access point is created.
     * For example, `installations/surelock-homes-hq`.
     *
     * Generated from protobuf field <code>string parent = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setParent($var)
    {
        GPBUtil::checkString($var, True);
        $this->parent = $var;

        return $this;
    }

    /**
     * The access point id to use for this access point. If it's
     * empty the server will autogenerate a unique identifier.
     *
     * Generated from protobuf field <code>optional string access_point_id = 2;</code>
     * @return string
     */
    public function getAccessPointId()
    {
        return isset($this->access_point_id) ? $this->access_point_id : '';
    }

    public function hasAccessPointId()
    {
        return isset($this->access_point_id);
    }

    public function clearAccessPointId()
    {
        unset($this->access_point_id);
    }

    /**
     * The access point id to use for this access point. If it's
     * empty the server will autogenerate a unique identifier.
     *
     * Generated from protobuf field <code>optional string access_point_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAccessPointId($var)
    {
        GPBUtil::checkString($var, True);
        $this->access_point_id = $var;

        return $this;
    }

    /**
     * The access point resource to be created. Client must not set the
     * `AccessPoint.name` field.
     *
     * Generated from protobuf field <code>.salto.nebula.accesspoint.v1.AccessPoint access_point = 3;</code>
     * @return \Saltoapis\Nebula\AccessPoint\V1\AccessPoint|null
     */
    public function getAccessPoint()
    {
        return $this->access_point;
    }

    public function hasAccessPoint()
    {
        return isset($this->access_point);
    }

    public function clearAccessPoint()
    {
        unset($this->access_point);
    }

    /**
     * The access point resource to be created. Client must not set the
     * `AccessPoint.name` field.
     *
     * Generated from protobuf field <code>.salto.nebula.accesspoint.v1.AccessPoint access_point = 3;</code>
     * @param \Saltoapis\Nebula\AccessPoint\V1\AccessPoint $var
     * @return $this
     */
    public function setAccessPoint($var)
    {
        GPBUtil::checkMessage($var, \Saltoapis\Nebula\AccessPoint\V1\AccessPoint::class);
        $this->access_point = $var;

        return $this;
    }

}

