<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: salto/nebula/event/v1/types.proto

namespace Saltoapis\Nebula\Event\V1\AccessDenied;

use UnexpectedValueException;

/**
 * The reason for the access denial.
 *
 * Protobuf type <code>salto.nebula.event.v1.AccessDenied.Reason</code>
 */
class Reason
{
    /**
     * The reason is not specified.
     *
     * Generated from protobuf enum <code>REASON_UNSPECIFIED = 0;</code>
     */
    const REASON_UNSPECIFIED = 0;
    /**
     * The presented credential has expired.
     *
     * Generated from protobuf enum <code>CREDENTIAL_EXPIRED = 1;</code>
     */
    const CREDENTIAL_EXPIRED = 1;
    /**
     * The provided key is not yet activated.
     * The key's activation date and time are scheduled for a future moment.
     *
     * Generated from protobuf enum <code>CREDENTIAL_UNACTIVATED = 2;</code>
     */
    const CREDENTIAL_UNACTIVATED = 2;
    /**
     * The provided credential does not have the required access rights.
     *
     * Generated from protobuf enum <code>CREDENTIAL_LACKS_ACCESS_RIGHTS = 3;</code>
     */
    const CREDENTIAL_LACKS_ACCESS_RIGHTS = 3;

    private static $valueToName = [
        self::REASON_UNSPECIFIED => 'REASON_UNSPECIFIED',
        self::CREDENTIAL_EXPIRED => 'CREDENTIAL_EXPIRED',
        self::CREDENTIAL_UNACTIVATED => 'CREDENTIAL_UNACTIVATED',
        self::CREDENTIAL_LACKS_ACCESS_RIGHTS => 'CREDENTIAL_LACKS_ACCESS_RIGHTS',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

