<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: salto/nebula/event/v1/types.proto

namespace Saltoapis\Nebula\Event\V1\AccessDenied;

use UnexpectedValueException;

/**
 * The reason for the access denial.
 *
 * Protobuf type <code>salto.nebula.event.v1.AccessDenied.Reason</code>
 */
class Reason
{
    /**
     * The reason is not specified.
     *
     * Generated from protobuf enum <code>REASON_UNSPECIFIED = 0;</code>
     */
    const REASON_UNSPECIFIED = 0;
    /**
     * The presented credential has expired and is no longer valid.
     * Example: the user's expiration date has passed.
     * Example: the user's key has expired. To prevent this,
     * renew the key before the installation's key-renewal-duration ends.
     *
     * Generated from protobuf enum <code>CREDENTIAL_EXPIRED = 1;</code>
     */
    const CREDENTIAL_EXPIRED = 1;
    /**
     * The provided key is not yet activated.
     * The key's activation date and time are scheduled for a future moment.
     * Example: the user's activation date has not yet been reached.
     *
     * Generated from protobuf enum <code>CREDENTIAL_UNACTIVATED = 2;</code>
     */
    const CREDENTIAL_UNACTIVATED = 2;
    /**
     * The provided credential does not have the required permission.
     * Example: the user does not have permission to access the access point.
     *
     * Generated from protobuf enum <code>CREDENTIAL_PERMISSION_INSUFFICIENT = 3;</code>
     */
    const CREDENTIAL_PERMISSION_INSUFFICIENT = 3;
    /**
     * The provided credential is permitted within the allowed schedule
     * but the permission is not activated at this time.
     * Example: access attempted before the activation date of the permission.
     * Example: access attempted after the expiration date of the permission.
     *
     * Generated from protobuf enum <code>CREDENTIAL_PERMISSION_OUTSIDE_VALIDITY = 4;</code>
     */
    const CREDENTIAL_PERMISSION_OUTSIDE_VALIDITY = 4;
    /**
     * The provided credential is not permitted within the allowed schedule.
     * Example: access attempted on a weekend for a weekday-only schedule.
     * Example: access attempted at 8 PM for a 9 AM-5 PM schedule).
     *
     * Generated from protobuf enum <code>CREDENTIAL_PERMISSION_OUTSIDE_SCHEDULE = 5;</code>
     */
    const CREDENTIAL_PERMISSION_OUTSIDE_SCHEDULE = 5;
    /**
     * The provided access code is invalid. Access codes are numeric passcodes
     * entered by users on a device keypad to gain access.
     * An access code may be considered invalid either if the entered digits
     * are incorrect or if the code does not meet required formatting rules.
     *
     * Generated from protobuf enum <code>INVALID_ACCESS_CODE = 6;</code>
     */
    const INVALID_ACCESS_CODE = 6;
    /**
     * The device at which the credential was presented has insufficient battery level
     * and cannot process the access request.
     *
     * Generated from protobuf enum <code>DEVICE_BATTERY_INSUFFICIENT = 7;</code>
     */
    const DEVICE_BATTERY_INSUFFICIENT = 7;

    private static $valueToName = [
        self::REASON_UNSPECIFIED => 'REASON_UNSPECIFIED',
        self::CREDENTIAL_EXPIRED => 'CREDENTIAL_EXPIRED',
        self::CREDENTIAL_UNACTIVATED => 'CREDENTIAL_UNACTIVATED',
        self::CREDENTIAL_PERMISSION_INSUFFICIENT => 'CREDENTIAL_PERMISSION_INSUFFICIENT',
        self::CREDENTIAL_PERMISSION_OUTSIDE_VALIDITY => 'CREDENTIAL_PERMISSION_OUTSIDE_VALIDITY',
        self::CREDENTIAL_PERMISSION_OUTSIDE_SCHEDULE => 'CREDENTIAL_PERMISSION_OUTSIDE_SCHEDULE',
        self::INVALID_ACCESS_CODE => 'INVALID_ACCESS_CODE',
        self::DEVICE_BATTERY_INSUFFICIENT => 'DEVICE_BATTERY_INSUFFICIENT',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

