<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: salto/nebula/serviceaccount/v1/service_account.proto

namespace Saltoapis\Nebula\ServiceAccount\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * The request message for [`GetServiceAccount`][salto.nebula.serviceaccount.v1.ServiceAccountService.GetServiceAccount]
 *
 * Generated from protobuf message <code>salto.nebula.serviceaccount.v1.GetServiceAccountRequest</code>
 */
class GetServiceAccountRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The name of the requested service account resource. For example:
     * `installations/surelock-homes-hq/service-accounts/my-service-account`.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           The name of the requested service account resource. For example:
     *           `installations/surelock-homes-hq/service-accounts/my-service-account`.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Saltoapis\Nebula\ServiceAccount\V1\ServiceAccount::initOnce();
        parent::__construct($data);
    }

    /**
     * The name of the requested service account resource. For example:
     * `installations/surelock-homes-hq/service-accounts/my-service-account`.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * The name of the requested service account resource. For example:
     * `installations/surelock-homes-hq/service-accounts/my-service-account`.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

}

