<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: salto/nebula/serviceaccount/v1/service_account.proto

namespace Saltoapis\Nebula\ServiceAccount\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * The service account object
 * A service account is an account for an application or a virtual machine (VM)
 * instance, not a person. You can use a service account to call Nebula APIs.
 * When you create a service account, you specify the installationID that owns the
 * service account, as well as a name that must be unique within the installation.
 *
 * Generated from protobuf message <code>salto.nebula.serviceaccount.v1.ServiceAccount</code>
 */
class ServiceAccount extends \Google\Protobuf\Internal\Message
{
    /**
     *  Resource name of the service account. It must have the format
     * `installations/{@*}service-accounts/*`. For example:
     * `installations/surelock-homes-hq/service-accounts/my-sa`.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Display name of the service account.
     *
     * Generated from protobuf field <code>string display_name = 2;</code>
     */
    protected $display_name = '';
    /**
     * OAuth client ID.
     *
     * Generated from protobuf field <code>string client_id = 3;</code>
     */
    protected $client_id = '';
    /**
     * Timestamp of when the service account was created.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp create_time = 4;</code>
     */
    protected $create_time = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *            Resource name of the service account. It must have the format
     *           `installations/{@*}service-accounts/*`. For example:
     *           `installations/surelock-homes-hq/service-accounts/my-sa`.
     *     @type string $display_name
     *           Display name of the service account.
     *     @type string $client_id
     *           OAuth client ID.
     *     @type \Google\Protobuf\Timestamp $create_time
     *           Timestamp of when the service account was created.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Saltoapis\Nebula\ServiceAccount\V1\ServiceAccount::initOnce();
        parent::__construct($data);
    }

    /**
     *  Resource name of the service account. It must have the format
     * `installations/{@*}service-accounts/*`. For example:
     * `installations/surelock-homes-hq/service-accounts/my-sa`.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     *  Resource name of the service account. It must have the format
     * `installations/{@*}service-accounts/*`. For example:
     * `installations/surelock-homes-hq/service-accounts/my-sa`.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Display name of the service account.
     *
     * Generated from protobuf field <code>string display_name = 2;</code>
     * @return string
     */
    public function getDisplayName()
    {
        return $this->display_name;
    }

    /**
     * Display name of the service account.
     *
     * Generated from protobuf field <code>string display_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDisplayName($var)
    {
        GPBUtil::checkString($var, True);
        $this->display_name = $var;

        return $this;
    }

    /**
     * OAuth client ID.
     *
     * Generated from protobuf field <code>string client_id = 3;</code>
     * @return string
     */
    public function getClientId()
    {
        return $this->client_id;
    }

    /**
     * OAuth client ID.
     *
     * Generated from protobuf field <code>string client_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setClientId($var)
    {
        GPBUtil::checkString($var, True);
        $this->client_id = $var;

        return $this;
    }

    /**
     * Timestamp of when the service account was created.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp create_time = 4;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getCreateTime()
    {
        return $this->create_time;
    }

    public function hasCreateTime()
    {
        return isset($this->create_time);
    }

    public function clearCreateTime()
    {
        unset($this->create_time);
    }

    /**
     * Timestamp of when the service account was created.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp create_time = 4;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setCreateTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->create_time = $var;

        return $this;
    }

}

