<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: salto/nebula/accessright/v1/access_right.proto

namespace Saltoapis\Nebula\AccessRight\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The request message for [`CreateAccessRightDestination`][salto.nebula.accessright.v1.AccessRightService.CreateAccessRightDestination]
 *
 * Generated from protobuf message <code>salto.nebula.accessright.v1.CreateAccessRightDestinationRequest</code>
 */
class CreateAccessRightDestinationRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Resource name of the parent resource where the access right's destination
     * association is to be created. For example:
     * `installations/surelock-homes-hq/access-rights/baskerville`.
     *
     * Generated from protobuf field <code>string parent = 1;</code>
     */
    protected $parent = '';
    /**
     * The access right's destination association resource to be created.
     * Client must not set the `AccessRightDestination.name` field.
     *
     * Generated from protobuf field <code>.salto.nebula.accessright.v1.AccessRightDestination access_right_destination = 2;</code>
     */
    protected $access_right_destination = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $parent
     *           Resource name of the parent resource where the access right's destination
     *           association is to be created. For example:
     *           `installations/surelock-homes-hq/access-rights/baskerville`.
     *     @type \Saltoapis\Nebula\AccessRight\V1\AccessRightDestination $access_right_destination
     *           The access right's destination association resource to be created.
     *           Client must not set the `AccessRightDestination.name` field.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Saltoapis\Nebula\AccessRight\V1\AccessRight::initOnce();
        parent::__construct($data);
    }

    /**
     * Resource name of the parent resource where the access right's destination
     * association is to be created. For example:
     * `installations/surelock-homes-hq/access-rights/baskerville`.
     *
     * Generated from protobuf field <code>string parent = 1;</code>
     * @return string
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * Resource name of the parent resource where the access right's destination
     * association is to be created. For example:
     * `installations/surelock-homes-hq/access-rights/baskerville`.
     *
     * Generated from protobuf field <code>string parent = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setParent($var)
    {
        GPBUtil::checkString($var, True);
        $this->parent = $var;

        return $this;
    }

    /**
     * The access right's destination association resource to be created.
     * Client must not set the `AccessRightDestination.name` field.
     *
     * Generated from protobuf field <code>.salto.nebula.accessright.v1.AccessRightDestination access_right_destination = 2;</code>
     * @return \Saltoapis\Nebula\AccessRight\V1\AccessRightDestination|null
     */
    public function getAccessRightDestination()
    {
        return $this->access_right_destination;
    }

    public function hasAccessRightDestination()
    {
        return isset($this->access_right_destination);
    }

    public function clearAccessRightDestination()
    {
        unset($this->access_right_destination);
    }

    /**
     * The access right's destination association resource to be created.
     * Client must not set the `AccessRightDestination.name` field.
     *
     * Generated from protobuf field <code>.salto.nebula.accessright.v1.AccessRightDestination access_right_destination = 2;</code>
     * @param \Saltoapis\Nebula\AccessRight\V1\AccessRightDestination $var
     * @return $this
     */
    public function setAccessRightDestination($var)
    {
        GPBUtil::checkMessage($var, \Saltoapis\Nebula\AccessRight\V1\AccessRightDestination::class);
        $this->access_right_destination = $var;

        return $this;
    }

}

