<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: salto/nebula/accessright/v1/access_right.proto

namespace Saltoapis\Nebula\AccessRight\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * The request message for [`ListAccessRightAccessPoints`][salto.nebula.accessright.v1.AccessRightService.ListAccessRightAccessPoints]
 *
 * Generated from protobuf message <code>salto.nebula.accessright.v1.ListAccessRightAccessPointsResponse</code>
 */
class ListAccessRightAccessPointsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The field name should match the noun `access_right_access_points` in the
     * method name. There will be a maximum number of items returned based on
     * the `page_size` field in the request.
     *
     * Generated from protobuf field <code>repeated .salto.nebula.accessright.v1.AccessRightAccessPoint access_right_access_points = 1;</code>
     */
    private $access_right_access_points;
    /**
     * Token to retrieve the next page of results, or empty if there are no more
     * results in the list.
     *
     * Generated from protobuf field <code>string next_page_token = 2;</code>
     */
    protected $next_page_token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Saltoapis\Nebula\AccessRight\V1\AccessRightAccessPoint[] $access_right_access_points
     *           The field name should match the noun `access_right_access_points` in the
     *           method name. There will be a maximum number of items returned based on
     *           the `page_size` field in the request.
     *     @type string $next_page_token
     *           Token to retrieve the next page of results, or empty if there are no more
     *           results in the list.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Saltoapis\Nebula\AccessRight\V1\AccessRight::initOnce();
        parent::__construct($data);
    }

    /**
     * The field name should match the noun `access_right_access_points` in the
     * method name. There will be a maximum number of items returned based on
     * the `page_size` field in the request.
     *
     * Generated from protobuf field <code>repeated .salto.nebula.accessright.v1.AccessRightAccessPoint access_right_access_points = 1;</code>
     * @return RepeatedField<\Saltoapis\Nebula\AccessRight\V1\AccessRightAccessPoint>
     */
    public function getAccessRightAccessPoints()
    {
        return $this->access_right_access_points;
    }

    /**
     * The field name should match the noun `access_right_access_points` in the
     * method name. There will be a maximum number of items returned based on
     * the `page_size` field in the request.
     *
     * Generated from protobuf field <code>repeated .salto.nebula.accessright.v1.AccessRightAccessPoint access_right_access_points = 1;</code>
     * @param \Saltoapis\Nebula\AccessRight\V1\AccessRightAccessPoint[] $var
     * @return $this
     */
    public function setAccessRightAccessPoints($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Saltoapis\Nebula\AccessRight\V1\AccessRightAccessPoint::class);
        $this->access_right_access_points = $arr;

        return $this;
    }

    /**
     * Token to retrieve the next page of results, or empty if there are no more
     * results in the list.
     *
     * Generated from protobuf field <code>string next_page_token = 2;</code>
     * @return string
     */
    public function getNextPageToken()
    {
        return $this->next_page_token;
    }

    /**
     * Token to retrieve the next page of results, or empty if there are no more
     * results in the list.
     *
     * Generated from protobuf field <code>string next_page_token = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNextPageToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->next_page_token = $var;

        return $this;
    }

}

