<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: salto/nebula/accessright/v1/access_right.proto

namespace Saltoapis\Nebula\AccessRight\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The request message for [`UpdateAccessRightDestination`][salto.nebula.accessright.v1.AccessRightService.UpdateAccessRightDestination]
 *
 * Generated from protobuf message <code>salto.nebula.accessright.v1.UpdateAccessRightDestinationRequest</code>
 */
class UpdateAccessRightDestinationRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The access right's destination resource which replaces the resource on
     * the server.
     *
     * Generated from protobuf field <code>.salto.nebula.accessright.v1.AccessRightDestination access_right_destination = 1;</code>
     */
    protected $access_right_destination = null;
    /**
     * The update mask applied to the resource.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask update_mask = 2;</code>
     */
    protected $update_mask = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Saltoapis\Nebula\AccessRight\V1\AccessRightDestination $access_right_destination
     *           The access right's destination resource which replaces the resource on
     *           the server.
     *     @type \Google\Protobuf\FieldMask $update_mask
     *           The update mask applied to the resource.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Saltoapis\Nebula\AccessRight\V1\AccessRight::initOnce();
        parent::__construct($data);
    }

    /**
     * The access right's destination resource which replaces the resource on
     * the server.
     *
     * Generated from protobuf field <code>.salto.nebula.accessright.v1.AccessRightDestination access_right_destination = 1;</code>
     * @return \Saltoapis\Nebula\AccessRight\V1\AccessRightDestination|null
     */
    public function getAccessRightDestination()
    {
        return $this->access_right_destination;
    }

    public function hasAccessRightDestination()
    {
        return isset($this->access_right_destination);
    }

    public function clearAccessRightDestination()
    {
        unset($this->access_right_destination);
    }

    /**
     * The access right's destination resource which replaces the resource on
     * the server.
     *
     * Generated from protobuf field <code>.salto.nebula.accessright.v1.AccessRightDestination access_right_destination = 1;</code>
     * @param \Saltoapis\Nebula\AccessRight\V1\AccessRightDestination $var
     * @return $this
     */
    public function setAccessRightDestination($var)
    {
        GPBUtil::checkMessage($var, \Saltoapis\Nebula\AccessRight\V1\AccessRightDestination::class);
        $this->access_right_destination = $var;

        return $this;
    }

    /**
     * The update mask applied to the resource.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask update_mask = 2;</code>
     * @return \Google\Protobuf\FieldMask|null
     */
    public function getUpdateMask()
    {
        return $this->update_mask;
    }

    public function hasUpdateMask()
    {
        return isset($this->update_mask);
    }

    public function clearUpdateMask()
    {
        unset($this->update_mask);
    }

    /**
     * The update mask applied to the resource.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask update_mask = 2;</code>
     * @param \Google\Protobuf\FieldMask $var
     * @return $this
     */
    public function setUpdateMask($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\FieldMask::class);
        $this->update_mask = $var;

        return $this;
    }

}

