<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: salto/nebula/type/local_operation.proto

namespace Saltoapis\Nebula\Type;

use UnexpectedValueException;

/**
 * Specifies a local operation that an app key can perform on an access
 * point via a mobile phone.
 *
 * Protobuf type <code>salto.nebula.type.AppKeyLocalOperation</code>
 */
class AppKeyLocalOperation
{
    /**
     * Unspecified. This value is not allowed and will be rejected by the API.
     *
     * Generated from protobuf enum <code>APP_KEY_LOCAL_OPERATION_UNSPECIFIED = 0;</code>
     */
    const APP_KEY_LOCAL_OPERATION_UNSPECIFIED = 0;
    /**
     * Locally unlocks the access point.
     *
     * Generated from protobuf enum <code>APP_KEY_LOCAL_OPERATION_UNLOCK = 1;</code>
     */
    const APP_KEY_LOCAL_OPERATION_UNLOCK = 1;
    /**
     * Locally locks the access point.
     *
     * Generated from protobuf enum <code>APP_KEY_LOCAL_OPERATION_LOCK = 2;</code>
     */
    const APP_KEY_LOCAL_OPERATION_LOCK = 2;
    /**
     * Locally enables office mode on the access point.
     *
     * Generated from protobuf enum <code>APP_KEY_LOCAL_OPERATION_OFFICE = 3;</code>
     */
    const APP_KEY_LOCAL_OPERATION_OFFICE = 3;

    private static $valueToName = [
        self::APP_KEY_LOCAL_OPERATION_UNSPECIFIED => 'APP_KEY_LOCAL_OPERATION_UNSPECIFIED',
        self::APP_KEY_LOCAL_OPERATION_UNLOCK => 'APP_KEY_LOCAL_OPERATION_UNLOCK',
        self::APP_KEY_LOCAL_OPERATION_LOCK => 'APP_KEY_LOCAL_OPERATION_LOCK',
        self::APP_KEY_LOCAL_OPERATION_OFFICE => 'APP_KEY_LOCAL_OPERATION_OFFICE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

