<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: salto/nebula/type/technology.proto

namespace Saltoapis\Nebula\Type;

use UnexpectedValueException;

/**
 * Specifies the technology used by the app to open an access point.
 *
 * Protobuf type <code>salto.nebula.type.AppKeyTechnology</code>
 */
class AppKeyTechnology
{
    /**
     * Unspecified or unknown technology.
     *
     * Generated from protobuf enum <code>APP_KEY_TECHNOLOGY_UNSPECIFIED = 0;</code>
     */
    const APP_KEY_TECHNOLOGY_UNSPECIFIED = 0;
    /**
     * Access via Bluetooth Low Energy (BLE).
     * The app communicates directly with the access point over Bluetooth Low
     * Energy to open it.
     *
     * Generated from protobuf enum <code>BLE = 1;</code>
     */
    const BLE = 1;
    /**
     * Access via Host Card Emulation (HCE).
     * The phone's role is CARD EMULATOR. It emulates a virtual key card
     * for the access point's reader to scan.
     *
     * Generated from protobuf enum <code>NFC_HCE = 2;</code>
     */
    const NFC_HCE = 2;
    /**
     * Access via NFC Reader Mode.
     * The phone's role is READER. It actively reads/writes to the
     * access point's passive NFC tag to authenticate and open it.
     *
     * Generated from protobuf enum <code>NFC_READER = 3;</code>
     */
    const NFC_READER = 3;

    private static $valueToName = [
        self::APP_KEY_TECHNOLOGY_UNSPECIFIED => 'APP_KEY_TECHNOLOGY_UNSPECIFIED',
        self::BLE => 'BLE',
        self::NFC_HCE => 'NFC_HCE',
        self::NFC_READER => 'NFC_READER',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

