<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: salto/longrunning/v1/operation.proto

namespace GPBMetadata\Saltoapis\Longrunning\V1;

class Operation
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Any::initOnce();
        \GPBMetadata\Google\Protobuf\GPBEmpty::initOnce();
        \GPBMetadata\Google\Rpc\Status::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xB9\x09\x0A\$salto/longrunning/v1/operation.proto\x12\x14salto.longrunning.v1\x1A\x1Bgoogle/protobuf/empty.proto\x1A\x17google/rpc/status.proto\"\xA8\x01\x0A\x09Operation\x12\x0C\x0A\x04name\x18\x01 \x01(\x09\x12&\x0A\x08metadata\x18\x02 \x01(\x0B2\x14.google.protobuf.Any\x12\x0C\x0A\x04done\x18\x03 \x01(\x08\x12#\x0A\x05error\x18\x04 \x01(\x0B2\x12.google.rpc.StatusH\x00\x12(\x0A\x08response\x18\x05 \x01(\x0B2\x14.google.protobuf.AnyH\x00B\x08\x0A\x06result\"#\x0A\x13GetOperationRequest\x12\x0C\x0A\x04name\x18\x01 \x01(\x09\"N\x0A\x15ListOperationsRequest\x12\x11\x0A\x09page_size\x18\x01 \x01(\x05\x12\x12\x0A\x0Apage_token\x18\x02 \x01(\x09\x12\x0E\x0A\x06filter\x18\x03 \x01(\x09\"f\x0A\x16ListOperationsResponse\x123\x0A\x0Aoperations\x18\x01 \x03(\x0B2\x1F.salto.longrunning.v1.Operation\x12\x17\x0A\x0Fnext_page_token\x18\x02 \x01(\x09\"&\x0A\x16DeleteOperationRequest\x12\x0C\x0A\x04name\x18\x01 \x01(\x09\"&\x0A\x16CancelOperationRequest\x12\x0C\x0A\x04name\x18\x01 \x01(\x092\x8D\x03\x0A\x10OperationService\x12Z\x0A\x0CGetOperation\x12).salto.longrunning.v1.GetOperationRequest\x1A\x1F.salto.longrunning.v1.Operation\x12k\x0A\x0EListOperations\x12+.salto.longrunning.v1.ListOperationsRequest\x1A,.salto.longrunning.v1.ListOperationsResponse\x12W\x0A\x0FDeleteOperation\x12,.salto.longrunning.v1.DeleteOperationRequest\x1A\x16.google.protobuf.Empty\x12W\x0A\x0FCancelOperation\x12,.salto.longrunning.v1.CancelOperationRequest\x1A\x16.google.protobuf.EmptyB\xD4\x01\x0A\x1Ccom.saltoapis.longrunning.v1B\x0EOperationProtoP\x01ZEgithub.com/saltoapis-internal/saltoapis-go/longrunning/v1;longrunning\xAA\x02\x18Saltoapis.Longrunning.V1\xCA\x02\x18Saltoapis\\Longrunning\\V1\xE2\x02\$GPBMetadata\\Saltoapis\\Longrunning\\V1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

