<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: salto/nebula/emergencykey/v1/emergency_key.proto

namespace Saltoapis\Nebula\EmergencyKey\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The request message for [`CreateEmergencyKey`][salto.nebula.emergencykey.v1.EmergencyKeyService.CreateEmergencyKey].
 *
 * Generated from protobuf message <code>salto.nebula.emergencykey.v1.CreateEmergencyKeyRequest</code>
 */
class CreateEmergencyKeyRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Resource name of the parent resource where the access right is to be
     * created. For example: ìnstallations/surelock-homes-hq`.
     *
     * Generated from protobuf field <code>string parent = 1;</code>
     */
    protected $parent = '';
    /**
     * The emergency key resource to be created. Client must not set the
     * `EmergencyKey.name` field.
     *
     * Generated from protobuf field <code>.salto.nebula.emergencykey.v1.EmergencyKey emergency_key = 3;</code>
     */
    protected $emergency_key = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $parent
     *           Resource name of the parent resource where the access right is to be
     *           created. For example: ìnstallations/surelock-homes-hq`.
     *     @type \Saltoapis\Nebula\EmergencyKey\V1\EmergencyKey $emergency_key
     *           The emergency key resource to be created. Client must not set the
     *           `EmergencyKey.name` field.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Saltoapis\Nebula\EmergencyKey\V1\EmergencyKey::initOnce();
        parent::__construct($data);
    }

    /**
     * Resource name of the parent resource where the access right is to be
     * created. For example: ìnstallations/surelock-homes-hq`.
     *
     * Generated from protobuf field <code>string parent = 1;</code>
     * @return string
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * Resource name of the parent resource where the access right is to be
     * created. For example: ìnstallations/surelock-homes-hq`.
     *
     * Generated from protobuf field <code>string parent = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setParent($var)
    {
        GPBUtil::checkString($var, True);
        $this->parent = $var;

        return $this;
    }

    /**
     * The emergency key resource to be created. Client must not set the
     * `EmergencyKey.name` field.
     *
     * Generated from protobuf field <code>.salto.nebula.emergencykey.v1.EmergencyKey emergency_key = 3;</code>
     * @return \Saltoapis\Nebula\EmergencyKey\V1\EmergencyKey|null
     */
    public function getEmergencyKey()
    {
        return $this->emergency_key;
    }

    public function hasEmergencyKey()
    {
        return isset($this->emergency_key);
    }

    public function clearEmergencyKey()
    {
        unset($this->emergency_key);
    }

    /**
     * The emergency key resource to be created. Client must not set the
     * `EmergencyKey.name` field.
     *
     * Generated from protobuf field <code>.salto.nebula.emergencykey.v1.EmergencyKey emergency_key = 3;</code>
     * @param \Saltoapis\Nebula\EmergencyKey\V1\EmergencyKey $var
     * @return $this
     */
    public function setEmergencyKey($var)
    {
        GPBUtil::checkMessage($var, \Saltoapis\Nebula\EmergencyKey\V1\EmergencyKey::class);
        $this->emergency_key = $var;

        return $this;
    }

}

