<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: salto/nebula/emergencykey/v1/emergency_key.proto

namespace Saltoapis\Nebula\EmergencyKey\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The request message for [`GetEmergencyKey`][salto.nebula.emergencykey.v1.EmergencyKeyService.GetEmergencyKey].
 *
 * Generated from protobuf message <code>salto.nebula.emergencykey.v1.GetEmergencyKeyRequest</code>
 */
class GetEmergencyKeyRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The name of the requested emergency key resource. For example:
     * `installations/surelock-homes-hq/emergency-keys/firefighters`.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           The name of the requested emergency key resource. For example:
     *           `installations/surelock-homes-hq/emergency-keys/firefighters`.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Saltoapis\Nebula\EmergencyKey\V1\EmergencyKey::initOnce();
        parent::__construct($data);
    }

    /**
     * The name of the requested emergency key resource. For example:
     * `installations/surelock-homes-hq/emergency-keys/firefighters`.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * The name of the requested emergency key resource. For example:
     * `installations/surelock-homes-hq/emergency-keys/firefighters`.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

}

