<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: salto/nebula/controller/v1/controller.proto

namespace Saltoapis\Nebula\Controller\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The request message for [`BatchCreateControllerRelays`][salto.nebula.controller.v1.ControllerService.BatchCreateControllerRelays]
 *
 * Generated from protobuf message <code>salto.nebula.controller.v1.BatchCreateControllerRelaysRequest</code>
 */
class BatchCreateControllerRelaysRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Resource name of the parent resource where the controller relays are to be created.
     * For example: `installations/surelock-homes-hq/controllers/dancing-men`.
     *
     * Generated from protobuf field <code>string parent = 1;</code>
     */
    protected $parent = '';
    /**
     * The request message specifying the resources to create.
     * A maximum of 100 controller relays can be created in a batch.
     *
     * Generated from protobuf field <code>repeated .salto.nebula.controller.v1.CreateControllerRelayRequest requests = 2;</code>
     */
    private $requests;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $parent
     *           Resource name of the parent resource where the controller relays are to be created.
     *           For example: `installations/surelock-homes-hq/controllers/dancing-men`.
     *     @type array<\Saltoapis\Nebula\Controller\V1\CreateControllerRelayRequest>|\Google\Protobuf\Internal\RepeatedField $requests
     *           The request message specifying the resources to create.
     *           A maximum of 100 controller relays can be created in a batch.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Saltoapis\Nebula\Controller\V1\Controller::initOnce();
        parent::__construct($data);
    }

    /**
     * Resource name of the parent resource where the controller relays are to be created.
     * For example: `installations/surelock-homes-hq/controllers/dancing-men`.
     *
     * Generated from protobuf field <code>string parent = 1;</code>
     * @return string
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * Resource name of the parent resource where the controller relays are to be created.
     * For example: `installations/surelock-homes-hq/controllers/dancing-men`.
     *
     * Generated from protobuf field <code>string parent = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setParent($var)
    {
        GPBUtil::checkString($var, True);
        $this->parent = $var;

        return $this;
    }

    /**
     * The request message specifying the resources to create.
     * A maximum of 100 controller relays can be created in a batch.
     *
     * Generated from protobuf field <code>repeated .salto.nebula.controller.v1.CreateControllerRelayRequest requests = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRequests()
    {
        return $this->requests;
    }

    /**
     * The request message specifying the resources to create.
     * A maximum of 100 controller relays can be created in a batch.
     *
     * Generated from protobuf field <code>repeated .salto.nebula.controller.v1.CreateControllerRelayRequest requests = 2;</code>
     * @param array<\Saltoapis\Nebula\Controller\V1\CreateControllerRelayRequest>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRequests($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Saltoapis\Nebula\Controller\V1\CreateControllerRelayRequest::class);
        $this->requests = $arr;

        return $this;
    }

}

