<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: salto/nebula/controller/v1/controller.proto

namespace Saltoapis\Nebula\Controller\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The request message for [CreateController][salto.nebula.controller.v1.ControllerService.CreateController]
 *
 * Generated from protobuf message <code>salto.nebula.controller.v1.CreateControllerRequest</code>
 */
class CreateControllerRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Resource name of the parent resource where to create the controller. For
     * example, `installations/surelock-homes-hq`.
     *
     * Generated from protobuf field <code>string parent = 1;</code>
     */
    protected $parent = '';
    /**
     * The controller ID to use for this controller. In case it's empty the
     * server will autogenerate a unique identifier.
     *
     * Generated from protobuf field <code>optional string controller_id = 2;</code>
     */
    protected $controller_id = null;
    /**
     * The controller resource to be created. Client must not set the
     * `Controller.name` field.
     *
     * Generated from protobuf field <code>.salto.nebula.controller.v1.Controller controller = 3;</code>
     */
    protected $controller = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $parent
     *           Resource name of the parent resource where to create the controller. For
     *           example, `installations/surelock-homes-hq`.
     *     @type string $controller_id
     *           The controller ID to use for this controller. In case it's empty the
     *           server will autogenerate a unique identifier.
     *     @type \Saltoapis\Nebula\Controller\V1\Controller $controller
     *           The controller resource to be created. Client must not set the
     *           `Controller.name` field.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Saltoapis\Nebula\Controller\V1\Controller::initOnce();
        parent::__construct($data);
    }

    /**
     * Resource name of the parent resource where to create the controller. For
     * example, `installations/surelock-homes-hq`.
     *
     * Generated from protobuf field <code>string parent = 1;</code>
     * @return string
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * Resource name of the parent resource where to create the controller. For
     * example, `installations/surelock-homes-hq`.
     *
     * Generated from protobuf field <code>string parent = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setParent($var)
    {
        GPBUtil::checkString($var, True);
        $this->parent = $var;

        return $this;
    }

    /**
     * The controller ID to use for this controller. In case it's empty the
     * server will autogenerate a unique identifier.
     *
     * Generated from protobuf field <code>optional string controller_id = 2;</code>
     * @return string
     */
    public function getControllerId()
    {
        return isset($this->controller_id) ? $this->controller_id : '';
    }

    public function hasControllerId()
    {
        return isset($this->controller_id);
    }

    public function clearControllerId()
    {
        unset($this->controller_id);
    }

    /**
     * The controller ID to use for this controller. In case it's empty the
     * server will autogenerate a unique identifier.
     *
     * Generated from protobuf field <code>optional string controller_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setControllerId($var)
    {
        GPBUtil::checkString($var, True);
        $this->controller_id = $var;

        return $this;
    }

    /**
     * The controller resource to be created. Client must not set the
     * `Controller.name` field.
     *
     * Generated from protobuf field <code>.salto.nebula.controller.v1.Controller controller = 3;</code>
     * @return \Saltoapis\Nebula\Controller\V1\Controller|null
     */
    public function getController()
    {
        return $this->controller;
    }

    public function hasController()
    {
        return isset($this->controller);
    }

    public function clearController()
    {
        unset($this->controller);
    }

    /**
     * The controller resource to be created. Client must not set the
     * `Controller.name` field.
     *
     * Generated from protobuf field <code>.salto.nebula.controller.v1.Controller controller = 3;</code>
     * @param \Saltoapis\Nebula\Controller\V1\Controller $var
     * @return $this
     */
    public function setController($var)
    {
        GPBUtil::checkMessage($var, \Saltoapis\Nebula\Controller\V1\Controller::class);
        $this->controller = $var;

        return $this;
    }

}

