<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: salto/nebula/event/v1/types.proto

namespace Saltoapis\Nebula\Event\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Event representing the update of an access point.
 *
 * Generated from protobuf message <code>salto.nebula.event.v1.AccessPointUpdated</code>
 */
class AccessPointUpdated extends \Google\Protobuf\Internal\Message
{
    /**
     * Access point updated.
     *
     * Generated from protobuf field <code>.salto.nebula.accesspoint.v1.AccessPoint access_point = 1;</code>
     */
    protected $access_point = null;
    /**
     * The actor who updated the access point.
     *
     * Generated from protobuf field <code>.salto.nebula.event.v1.Principal actor = 2;</code>
     */
    protected $actor = null;
    /**
     * The previous values of the access point's fields that were changed.
     *
     * Generated from protobuf field <code>.salto.nebula.event.v1.PreviousValues previous_values = 3;</code>
     */
    protected $previous_values = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Saltoapis\Nebula\AccessPoint\V1\AccessPoint $access_point
     *           Access point updated.
     *     @type \Saltoapis\Nebula\Event\V1\Principal $actor
     *           The actor who updated the access point.
     *     @type \Saltoapis\Nebula\Event\V1\PreviousValues $previous_values
     *           The previous values of the access point's fields that were changed.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Saltoapis\Nebula\Event\V1\Types::initOnce();
        parent::__construct($data);
    }

    /**
     * Access point updated.
     *
     * Generated from protobuf field <code>.salto.nebula.accesspoint.v1.AccessPoint access_point = 1;</code>
     * @return \Saltoapis\Nebula\AccessPoint\V1\AccessPoint|null
     */
    public function getAccessPoint()
    {
        return $this->access_point;
    }

    public function hasAccessPoint()
    {
        return isset($this->access_point);
    }

    public function clearAccessPoint()
    {
        unset($this->access_point);
    }

    /**
     * Access point updated.
     *
     * Generated from protobuf field <code>.salto.nebula.accesspoint.v1.AccessPoint access_point = 1;</code>
     * @param \Saltoapis\Nebula\AccessPoint\V1\AccessPoint $var
     * @return $this
     */
    public function setAccessPoint($var)
    {
        GPBUtil::checkMessage($var, \Saltoapis\Nebula\AccessPoint\V1\AccessPoint::class);
        $this->access_point = $var;

        return $this;
    }

    /**
     * The actor who updated the access point.
     *
     * Generated from protobuf field <code>.salto.nebula.event.v1.Principal actor = 2;</code>
     * @return \Saltoapis\Nebula\Event\V1\Principal|null
     */
    public function getActor()
    {
        return $this->actor;
    }

    public function hasActor()
    {
        return isset($this->actor);
    }

    public function clearActor()
    {
        unset($this->actor);
    }

    /**
     * The actor who updated the access point.
     *
     * Generated from protobuf field <code>.salto.nebula.event.v1.Principal actor = 2;</code>
     * @param \Saltoapis\Nebula\Event\V1\Principal $var
     * @return $this
     */
    public function setActor($var)
    {
        GPBUtil::checkMessage($var, \Saltoapis\Nebula\Event\V1\Principal::class);
        $this->actor = $var;

        return $this;
    }

    /**
     * The previous values of the access point's fields that were changed.
     *
     * Generated from protobuf field <code>.salto.nebula.event.v1.PreviousValues previous_values = 3;</code>
     * @return \Saltoapis\Nebula\Event\V1\PreviousValues|null
     */
    public function getPreviousValues()
    {
        return $this->previous_values;
    }

    public function hasPreviousValues()
    {
        return isset($this->previous_values);
    }

    public function clearPreviousValues()
    {
        unset($this->previous_values);
    }

    /**
     * The previous values of the access point's fields that were changed.
     *
     * Generated from protobuf field <code>.salto.nebula.event.v1.PreviousValues previous_values = 3;</code>
     * @param \Saltoapis\Nebula\Event\V1\PreviousValues $var
     * @return $this
     */
    public function setPreviousValues($var)
    {
        GPBUtil::checkMessage($var, \Saltoapis\Nebula\Event\V1\PreviousValues::class);
        $this->previous_values = $var;

        return $this;
    }

}

