<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: salto/nebula/event/v1/types.proto

namespace Saltoapis\Nebula\Event\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Event representing the update of a unit.
 *
 * Generated from protobuf message <code>salto.nebula.event.v1.UnitUpdated</code>
 */
class UnitUpdated extends \Google\Protobuf\Internal\Message
{
    /**
     * Unit updated.
     *
     * Generated from protobuf field <code>.salto.nebula.unit.v1.Unit unit = 1;</code>
     */
    protected $unit = null;
    /**
     * The actor who updated the unit.
     *
     * Generated from protobuf field <code>.salto.nebula.event.v1.Principal actor = 2;</code>
     */
    protected $actor = null;
    /**
     * The previous values of the unit's fields that were changed.
     *
     * Generated from protobuf field <code>.salto.nebula.event.v1.PreviousValues previous_values = 3;</code>
     */
    protected $previous_values = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Saltoapis\Nebula\Unit\V1\Unit $unit
     *           Unit updated.
     *     @type \Saltoapis\Nebula\Event\V1\Principal $actor
     *           The actor who updated the unit.
     *     @type \Saltoapis\Nebula\Event\V1\PreviousValues $previous_values
     *           The previous values of the unit's fields that were changed.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Saltoapis\Nebula\Event\V1\Types::initOnce();
        parent::__construct($data);
    }

    /**
     * Unit updated.
     *
     * Generated from protobuf field <code>.salto.nebula.unit.v1.Unit unit = 1;</code>
     * @return \Saltoapis\Nebula\Unit\V1\Unit|null
     */
    public function getUnit()
    {
        return $this->unit;
    }

    public function hasUnit()
    {
        return isset($this->unit);
    }

    public function clearUnit()
    {
        unset($this->unit);
    }

    /**
     * Unit updated.
     *
     * Generated from protobuf field <code>.salto.nebula.unit.v1.Unit unit = 1;</code>
     * @param \Saltoapis\Nebula\Unit\V1\Unit $var
     * @return $this
     */
    public function setUnit($var)
    {
        GPBUtil::checkMessage($var, \Saltoapis\Nebula\Unit\V1\Unit::class);
        $this->unit = $var;

        return $this;
    }

    /**
     * The actor who updated the unit.
     *
     * Generated from protobuf field <code>.salto.nebula.event.v1.Principal actor = 2;</code>
     * @return \Saltoapis\Nebula\Event\V1\Principal|null
     */
    public function getActor()
    {
        return $this->actor;
    }

    public function hasActor()
    {
        return isset($this->actor);
    }

    public function clearActor()
    {
        unset($this->actor);
    }

    /**
     * The actor who updated the unit.
     *
     * Generated from protobuf field <code>.salto.nebula.event.v1.Principal actor = 2;</code>
     * @param \Saltoapis\Nebula\Event\V1\Principal $var
     * @return $this
     */
    public function setActor($var)
    {
        GPBUtil::checkMessage($var, \Saltoapis\Nebula\Event\V1\Principal::class);
        $this->actor = $var;

        return $this;
    }

    /**
     * The previous values of the unit's fields that were changed.
     *
     * Generated from protobuf field <code>.salto.nebula.event.v1.PreviousValues previous_values = 3;</code>
     * @return \Saltoapis\Nebula\Event\V1\PreviousValues|null
     */
    public function getPreviousValues()
    {
        return $this->previous_values;
    }

    public function hasPreviousValues()
    {
        return isset($this->previous_values);
    }

    public function clearPreviousValues()
    {
        unset($this->previous_values);
    }

    /**
     * The previous values of the unit's fields that were changed.
     *
     * Generated from protobuf field <code>.salto.nebula.event.v1.PreviousValues previous_values = 3;</code>
     * @param \Saltoapis\Nebula\Event\V1\PreviousValues $var
     * @return $this
     */
    public function setPreviousValues($var)
    {
        GPBUtil::checkMessage($var, \Saltoapis\Nebula\Event\V1\PreviousValues::class);
        $this->previous_values = $var;

        return $this;
    }

}

