<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: salto/nebula/event/v1/types.proto

namespace Saltoapis\Nebula\Event\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Event representing the update of a user.
 *
 * Generated from protobuf message <code>salto.nebula.event.v1.UserUpdated</code>
 */
class UserUpdated extends \Google\Protobuf\Internal\Message
{
    /**
     * User updated.
     *
     * Generated from protobuf field <code>.salto.nebula.user.v1.User user = 1;</code>
     */
    protected $user = null;
    /**
     * The actor who updated the user.
     *
     * Generated from protobuf field <code>.salto.nebula.event.v1.Principal actor = 2;</code>
     */
    protected $actor = null;
    /**
     * The previous values of the user's fields that were changed.
     *
     * Generated from protobuf field <code>.salto.nebula.event.v1.PreviousValues previous_values = 3;</code>
     */
    protected $previous_values = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Saltoapis\Nebula\User\V1\User $user
     *           User updated.
     *     @type \Saltoapis\Nebula\Event\V1\Principal $actor
     *           The actor who updated the user.
     *     @type \Saltoapis\Nebula\Event\V1\PreviousValues $previous_values
     *           The previous values of the user's fields that were changed.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Saltoapis\Nebula\Event\V1\Types::initOnce();
        parent::__construct($data);
    }

    /**
     * User updated.
     *
     * Generated from protobuf field <code>.salto.nebula.user.v1.User user = 1;</code>
     * @return \Saltoapis\Nebula\User\V1\User|null
     */
    public function getUser()
    {
        return $this->user;
    }

    public function hasUser()
    {
        return isset($this->user);
    }

    public function clearUser()
    {
        unset($this->user);
    }

    /**
     * User updated.
     *
     * Generated from protobuf field <code>.salto.nebula.user.v1.User user = 1;</code>
     * @param \Saltoapis\Nebula\User\V1\User $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkMessage($var, \Saltoapis\Nebula\User\V1\User::class);
        $this->user = $var;

        return $this;
    }

    /**
     * The actor who updated the user.
     *
     * Generated from protobuf field <code>.salto.nebula.event.v1.Principal actor = 2;</code>
     * @return \Saltoapis\Nebula\Event\V1\Principal|null
     */
    public function getActor()
    {
        return $this->actor;
    }

    public function hasActor()
    {
        return isset($this->actor);
    }

    public function clearActor()
    {
        unset($this->actor);
    }

    /**
     * The actor who updated the user.
     *
     * Generated from protobuf field <code>.salto.nebula.event.v1.Principal actor = 2;</code>
     * @param \Saltoapis\Nebula\Event\V1\Principal $var
     * @return $this
     */
    public function setActor($var)
    {
        GPBUtil::checkMessage($var, \Saltoapis\Nebula\Event\V1\Principal::class);
        $this->actor = $var;

        return $this;
    }

    /**
     * The previous values of the user's fields that were changed.
     *
     * Generated from protobuf field <code>.salto.nebula.event.v1.PreviousValues previous_values = 3;</code>
     * @return \Saltoapis\Nebula\Event\V1\PreviousValues|null
     */
    public function getPreviousValues()
    {
        return $this->previous_values;
    }

    public function hasPreviousValues()
    {
        return isset($this->previous_values);
    }

    public function clearPreviousValues()
    {
        unset($this->previous_values);
    }

    /**
     * The previous values of the user's fields that were changed.
     *
     * Generated from protobuf field <code>.salto.nebula.event.v1.PreviousValues previous_values = 3;</code>
     * @param \Saltoapis\Nebula\Event\V1\PreviousValues $var
     * @return $this
     */
    public function setPreviousValues($var)
    {
        GPBUtil::checkMessage($var, \Saltoapis\Nebula\Event\V1\PreviousValues::class);
        $this->previous_values = $var;

        return $this;
    }

}

