<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: salto/nebula/event/v1/types.proto

namespace Saltoapis\Nebula\Event\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Event representing the update of a user's access right association.
 *
 * Generated from protobuf message <code>salto.nebula.event.v1.UserAccessRightUpdated</code>
 */
class UserAccessRightUpdated extends \Google\Protobuf\Internal\Message
{
    /**
     * Access right's user association updated.
     *
     * Generated from protobuf field <code>.salto.nebula.user.v1.User user = 1;</code>
     */
    protected $user = null;
    /**
     * User's access right association updated.
     *
     * Generated from protobuf field <code>.salto.nebula.accessright.v1.AccessRight access_right = 2;</code>
     */
    protected $access_right = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Saltoapis\Nebula\User\V1\User $user
     *           Access right's user association updated.
     *     @type \Saltoapis\Nebula\AccessRight\V1\AccessRight $access_right
     *           User's access right association updated.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Saltoapis\Nebula\Event\V1\Types::initOnce();
        parent::__construct($data);
    }

    /**
     * Access right's user association updated.
     *
     * Generated from protobuf field <code>.salto.nebula.user.v1.User user = 1;</code>
     * @return \Saltoapis\Nebula\User\V1\User|null
     */
    public function getUser()
    {
        return $this->user;
    }

    public function hasUser()
    {
        return isset($this->user);
    }

    public function clearUser()
    {
        unset($this->user);
    }

    /**
     * Access right's user association updated.
     *
     * Generated from protobuf field <code>.salto.nebula.user.v1.User user = 1;</code>
     * @param \Saltoapis\Nebula\User\V1\User $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkMessage($var, \Saltoapis\Nebula\User\V1\User::class);
        $this->user = $var;

        return $this;
    }

    /**
     * User's access right association updated.
     *
     * Generated from protobuf field <code>.salto.nebula.accessright.v1.AccessRight access_right = 2;</code>
     * @return \Saltoapis\Nebula\AccessRight\V1\AccessRight|null
     */
    public function getAccessRight()
    {
        return $this->access_right;
    }

    public function hasAccessRight()
    {
        return isset($this->access_right);
    }

    public function clearAccessRight()
    {
        unset($this->access_right);
    }

    /**
     * User's access right association updated.
     *
     * Generated from protobuf field <code>.salto.nebula.accessright.v1.AccessRight access_right = 2;</code>
     * @param \Saltoapis\Nebula\AccessRight\V1\AccessRight $var
     * @return $this
     */
    public function setAccessRight($var)
    {
        GPBUtil::checkMessage($var, \Saltoapis\Nebula\AccessRight\V1\AccessRight::class);
        $this->access_right = $var;

        return $this;
    }

}

