<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: salto/nebula/event/v1/types.proto

namespace Saltoapis\Nebula\Event\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Event representing the assignment of a user's wallet key.
 *
 * Generated from protobuf message <code>salto.nebula.event.v1.WalletKeyAssigned</code>
 */
class WalletKeyAssigned extends \Google\Protobuf\Internal\Message
{
    /**
     * Wallet key's user.
     *
     * Generated from protobuf field <code>.salto.nebula.user.v1.User user = 1;</code>
     */
    protected $user = null;
    /**
     * Wallet key assigned.
     *
     * Generated from protobuf field <code>.salto.nebula.user.v1.WalletKey wallet_key = 2;</code>
     */
    protected $wallet_key = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Saltoapis\Nebula\User\V1\User $user
     *           Wallet key's user.
     *     @type \Saltoapis\Nebula\User\V1\WalletKey $wallet_key
     *           Wallet key assigned.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Saltoapis\Nebula\Event\V1\Types::initOnce();
        parent::__construct($data);
    }

    /**
     * Wallet key's user.
     *
     * Generated from protobuf field <code>.salto.nebula.user.v1.User user = 1;</code>
     * @return \Saltoapis\Nebula\User\V1\User|null
     */
    public function getUser()
    {
        return $this->user;
    }

    public function hasUser()
    {
        return isset($this->user);
    }

    public function clearUser()
    {
        unset($this->user);
    }

    /**
     * Wallet key's user.
     *
     * Generated from protobuf field <code>.salto.nebula.user.v1.User user = 1;</code>
     * @param \Saltoapis\Nebula\User\V1\User $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkMessage($var, \Saltoapis\Nebula\User\V1\User::class);
        $this->user = $var;

        return $this;
    }

    /**
     * Wallet key assigned.
     *
     * Generated from protobuf field <code>.salto.nebula.user.v1.WalletKey wallet_key = 2;</code>
     * @return \Saltoapis\Nebula\User\V1\WalletKey|null
     */
    public function getWalletKey()
    {
        return $this->wallet_key;
    }

    public function hasWalletKey()
    {
        return isset($this->wallet_key);
    }

    public function clearWalletKey()
    {
        unset($this->wallet_key);
    }

    /**
     * Wallet key assigned.
     *
     * Generated from protobuf field <code>.salto.nebula.user.v1.WalletKey wallet_key = 2;</code>
     * @param \Saltoapis\Nebula\User\V1\WalletKey $var
     * @return $this
     */
    public function setWalletKey($var)
    {
        GPBUtil::checkMessage($var, \Saltoapis\Nebula\User\V1\WalletKey::class);
        $this->wallet_key = $var;

        return $this;
    }

}

