<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: salto/nebula/user/v1/user.proto

namespace Saltoapis\Nebula\User\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Representation of an app key, belonging to a user
 *
 * Generated from protobuf message <code>salto.nebula.user.v1.AppKey</code>
 */
class AppKey extends \Google\Protobuf\Internal\Message
{
    /**
     * Resource name of the user's app key. It must have the
     * format of `installations/{@*}users/{@*}app-key`. For example:
     * `installations/surelock-homes-hq/users/john-watson/app-key`.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Indicates whether this app key has been assigned or not. This field
     * cannot be modified using a standard
     * [`UpdateAppKey`][salto.nebula.user.v1.UserService.UpdateAppKey]
     * operation. To change the value of this field, you must call
     * [`AssignAppKey`][salto.nebula.user.v1.UserService.AssignAppKey].
     *
     * Generated from protobuf field <code>.salto.nebula.user.v1.AppKey.State state = 2;</code>
     */
    protected $state = 0;
    /**
     * Indicates whether this app key has pending updates or not.
     * This field cannot be modified using a standard
     * [`UpdateAppKey`][salto.nebula.user.v1.UserService.UpdateAppKey]
     * operation. To change the value of this field, you must call
     * [`OutdateAppKey`][salto.nebula.user.v1.UserService.OutdateAppKey].
     *
     * Generated from protobuf field <code>bool outdated = 3;</code>
     */
    protected $outdated = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           Resource name of the user's app key. It must have the
     *           format of `installations/{@*}users/{@*}app-key`. For example:
     *           `installations/surelock-homes-hq/users/john-watson/app-key`.
     *     @type int $state
     *           Indicates whether this app key has been assigned or not. This field
     *           cannot be modified using a standard
     *           [`UpdateAppKey`][salto.nebula.user.v1.UserService.UpdateAppKey]
     *           operation. To change the value of this field, you must call
     *           [`AssignAppKey`][salto.nebula.user.v1.UserService.AssignAppKey].
     *     @type bool $outdated
     *           Indicates whether this app key has pending updates or not.
     *           This field cannot be modified using a standard
     *           [`UpdateAppKey`][salto.nebula.user.v1.UserService.UpdateAppKey]
     *           operation. To change the value of this field, you must call
     *           [`OutdateAppKey`][salto.nebula.user.v1.UserService.OutdateAppKey].
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Saltoapis\Nebula\User\V1\User::initOnce();
        parent::__construct($data);
    }

    /**
     * Resource name of the user's app key. It must have the
     * format of `installations/{@*}users/{@*}app-key`. For example:
     * `installations/surelock-homes-hq/users/john-watson/app-key`.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Resource name of the user's app key. It must have the
     * format of `installations/{@*}users/{@*}app-key`. For example:
     * `installations/surelock-homes-hq/users/john-watson/app-key`.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Indicates whether this app key has been assigned or not. This field
     * cannot be modified using a standard
     * [`UpdateAppKey`][salto.nebula.user.v1.UserService.UpdateAppKey]
     * operation. To change the value of this field, you must call
     * [`AssignAppKey`][salto.nebula.user.v1.UserService.AssignAppKey].
     *
     * Generated from protobuf field <code>.salto.nebula.user.v1.AppKey.State state = 2;</code>
     * @return int
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * Indicates whether this app key has been assigned or not. This field
     * cannot be modified using a standard
     * [`UpdateAppKey`][salto.nebula.user.v1.UserService.UpdateAppKey]
     * operation. To change the value of this field, you must call
     * [`AssignAppKey`][salto.nebula.user.v1.UserService.AssignAppKey].
     *
     * Generated from protobuf field <code>.salto.nebula.user.v1.AppKey.State state = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setState($var)
    {
        GPBUtil::checkEnum($var, \Saltoapis\Nebula\User\V1\AppKey\State::class);
        $this->state = $var;

        return $this;
    }

    /**
     * Indicates whether this app key has pending updates or not.
     * This field cannot be modified using a standard
     * [`UpdateAppKey`][salto.nebula.user.v1.UserService.UpdateAppKey]
     * operation. To change the value of this field, you must call
     * [`OutdateAppKey`][salto.nebula.user.v1.UserService.OutdateAppKey].
     *
     * Generated from protobuf field <code>bool outdated = 3;</code>
     * @return bool
     */
    public function getOutdated()
    {
        return $this->outdated;
    }

    /**
     * Indicates whether this app key has pending updates or not.
     * This field cannot be modified using a standard
     * [`UpdateAppKey`][salto.nebula.user.v1.UserService.UpdateAppKey]
     * operation. To change the value of this field, you must call
     * [`OutdateAppKey`][salto.nebula.user.v1.UserService.OutdateAppKey].
     *
     * Generated from protobuf field <code>bool outdated = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setOutdated($var)
    {
        GPBUtil::checkBool($var);
        $this->outdated = $var;

        return $this;
    }

}

