<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: salto/nebula/user/v1/user.proto

namespace Saltoapis\Nebula\User\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Representation of an app key, belonging to a user
 *
 * Generated from protobuf message <code>salto.nebula.user.v1.AppKey</code>
 */
class AppKey extends \Google\Protobuf\Internal\Message
{
    /**
     * Resource name of the user's app key. It must have the
     * format of `installations/{@*}users/{@*}app-key`. For example:
     * `installations/surelock-homes-hq/users/john-watson/app-key`.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Indicates whether this app key has been assigned or not. This field
     * cannot be modified using a standard
     * [`UpdateAppKey`][salto.nebula.user.v1.UserService.UpdateAppKey]
     * operation. To change the value of this field, you must call
     * [`AssignAppKey`][salto.nebula.user.v1.UserService.AssignAppKey].
     *
     * Generated from protobuf field <code>.salto.nebula.user.v1.AppKey.State state = 2;</code>
     */
    protected $state = 0;
    /**
     * Indicates whether this app key has pending updates or not.
     * Deprecated: This field is deprecated and should not be used.
     *
     * Generated from protobuf field <code>bool outdated = 3;</code>
     */
    protected $outdated = false;
    /**
     * Allowed remote operations for the app key.
     *
     * Generated from protobuf field <code>repeated .salto.nebula.type.AppKeyRemoteOperation remote_operations = 4;</code>
     */
    private $remote_operations;
    /**
     * How access to the app key is managed. Determines whether a digital key
     * is created for this app key or not.
     *
     * Generated from protobuf field <code>.salto.nebula.user.v1.AppKey.Type type = 5;</code>
     */
    protected $type = 0;
    /**
     * The email identity to which the digital key was issued.
     * Set iff `type` is `MANAGED`. At the moment, this is always
     * set for managed app keys, as it is the email used for the digital key
     * binding.
     * This is an assignment-time snapshot and is not subsequently
     * synchronized with `User.email`.
     *
     * Generated from protobuf field <code>optional string email = 6;</code>
     */
    protected $email = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           Resource name of the user's app key. It must have the
     *           format of `installations/{@*}users/{@*}app-key`. For example:
     *           `installations/surelock-homes-hq/users/john-watson/app-key`.
     *     @type int $state
     *           Indicates whether this app key has been assigned or not. This field
     *           cannot be modified using a standard
     *           [`UpdateAppKey`][salto.nebula.user.v1.UserService.UpdateAppKey]
     *           operation. To change the value of this field, you must call
     *           [`AssignAppKey`][salto.nebula.user.v1.UserService.AssignAppKey].
     *     @type bool $outdated
     *           Indicates whether this app key has pending updates or not.
     *           Deprecated: This field is deprecated and should not be used.
     *     @type int[] $remote_operations
     *           Allowed remote operations for the app key.
     *     @type int $type
     *           How access to the app key is managed. Determines whether a digital key
     *           is created for this app key or not.
     *     @type string $email
     *           The email identity to which the digital key was issued.
     *           Set iff `type` is `MANAGED`. At the moment, this is always
     *           set for managed app keys, as it is the email used for the digital key
     *           binding.
     *           This is an assignment-time snapshot and is not subsequently
     *           synchronized with `User.email`.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Saltoapis\Nebula\User\V1\User::initOnce();
        parent::__construct($data);
    }

    /**
     * Resource name of the user's app key. It must have the
     * format of `installations/{@*}users/{@*}app-key`. For example:
     * `installations/surelock-homes-hq/users/john-watson/app-key`.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Resource name of the user's app key. It must have the
     * format of `installations/{@*}users/{@*}app-key`. For example:
     * `installations/surelock-homes-hq/users/john-watson/app-key`.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Indicates whether this app key has been assigned or not. This field
     * cannot be modified using a standard
     * [`UpdateAppKey`][salto.nebula.user.v1.UserService.UpdateAppKey]
     * operation. To change the value of this field, you must call
     * [`AssignAppKey`][salto.nebula.user.v1.UserService.AssignAppKey].
     *
     * Generated from protobuf field <code>.salto.nebula.user.v1.AppKey.State state = 2;</code>
     * @return int
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * Indicates whether this app key has been assigned or not. This field
     * cannot be modified using a standard
     * [`UpdateAppKey`][salto.nebula.user.v1.UserService.UpdateAppKey]
     * operation. To change the value of this field, you must call
     * [`AssignAppKey`][salto.nebula.user.v1.UserService.AssignAppKey].
     *
     * Generated from protobuf field <code>.salto.nebula.user.v1.AppKey.State state = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setState($var)
    {
        GPBUtil::checkEnum($var, \Saltoapis\Nebula\User\V1\AppKey\State::class);
        $this->state = $var;

        return $this;
    }

    /**
     * Indicates whether this app key has pending updates or not.
     * Deprecated: This field is deprecated and should not be used.
     *
     * Generated from protobuf field <code>bool outdated = 3;</code>
     * @return bool
     */
    public function getOutdated()
    {
        return $this->outdated;
    }

    /**
     * Indicates whether this app key has pending updates or not.
     * Deprecated: This field is deprecated and should not be used.
     *
     * Generated from protobuf field <code>bool outdated = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setOutdated($var)
    {
        GPBUtil::checkBool($var);
        $this->outdated = $var;

        return $this;
    }

    /**
     * Allowed remote operations for the app key.
     *
     * Generated from protobuf field <code>repeated .salto.nebula.type.AppKeyRemoteOperation remote_operations = 4;</code>
     * @return RepeatedField<int>
     */
    public function getRemoteOperations()
    {
        return $this->remote_operations;
    }

    /**
     * Allowed remote operations for the app key.
     *
     * Generated from protobuf field <code>repeated .salto.nebula.type.AppKeyRemoteOperation remote_operations = 4;</code>
     * @param int[] $var
     * @return $this
     */
    public function setRemoteOperations($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Saltoapis\Nebula\Type\AppKeyRemoteOperation::class);
        $this->remote_operations = $arr;

        return $this;
    }

    /**
     * How access to the app key is managed. Determines whether a digital key
     * is created for this app key or not.
     *
     * Generated from protobuf field <code>.salto.nebula.user.v1.AppKey.Type type = 5;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * How access to the app key is managed. Determines whether a digital key
     * is created for this app key or not.
     *
     * Generated from protobuf field <code>.salto.nebula.user.v1.AppKey.Type type = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Saltoapis\Nebula\User\V1\AppKey\Type::class);
        $this->type = $var;

        return $this;
    }

    /**
     * The email identity to which the digital key was issued.
     * Set iff `type` is `MANAGED`. At the moment, this is always
     * set for managed app keys, as it is the email used for the digital key
     * binding.
     * This is an assignment-time snapshot and is not subsequently
     * synchronized with `User.email`.
     *
     * Generated from protobuf field <code>optional string email = 6;</code>
     * @return string
     */
    public function getEmail()
    {
        return isset($this->email) ? $this->email : '';
    }

    public function hasEmail()
    {
        return isset($this->email);
    }

    public function clearEmail()
    {
        unset($this->email);
    }

    /**
     * The email identity to which the digital key was issued.
     * Set iff `type` is `MANAGED`. At the moment, this is always
     * set for managed app keys, as it is the email used for the digital key
     * binding.
     * This is an assignment-time snapshot and is not subsequently
     * synchronized with `User.email`.
     *
     * Generated from protobuf field <code>optional string email = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->email = $var;

        return $this;
    }

}

