<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: salto/nebula/user/v1/user.proto

namespace Saltoapis\Nebula\User\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The response message for [`AssignElectronicKey`][salto.nebula.user.v1.UserService.AssignElectronicKey]
 *
 * Generated from protobuf message <code>salto.nebula.user.v1.AssignElectronicKeyResponse</code>
 */
class AssignElectronicKeyResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The assigned electronic key.
     *
     * Generated from protobuf field <code>.salto.nebula.user.v1.ElectronicKey electronic_key = 1;</code>
     */
    protected $electronic_key = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Saltoapis\Nebula\User\V1\ElectronicKey $electronic_key
     *           The assigned electronic key.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Saltoapis\Nebula\User\V1\User::initOnce();
        parent::__construct($data);
    }

    /**
     * The assigned electronic key.
     *
     * Generated from protobuf field <code>.salto.nebula.user.v1.ElectronicKey electronic_key = 1;</code>
     * @return \Saltoapis\Nebula\User\V1\ElectronicKey|null
     */
    public function getElectronicKey()
    {
        return $this->electronic_key;
    }

    public function hasElectronicKey()
    {
        return isset($this->electronic_key);
    }

    public function clearElectronicKey()
    {
        unset($this->electronic_key);
    }

    /**
     * The assigned electronic key.
     *
     * Generated from protobuf field <code>.salto.nebula.user.v1.ElectronicKey electronic_key = 1;</code>
     * @param \Saltoapis\Nebula\User\V1\ElectronicKey $var
     * @return $this
     */
    public function setElectronicKey($var)
    {
        GPBUtil::checkMessage($var, \Saltoapis\Nebula\User\V1\ElectronicKey::class);
        $this->electronic_key = $var;

        return $this;
    }

}

