<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: salto/nebula/user/v1/user.proto

namespace Saltoapis\Nebula\User\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Representation of a passcode, belonging to a user
 *
 * Generated from protobuf message <code>salto.nebula.user.v1.Passcode</code>
 */
class Passcode extends \Google\Protobuf\Internal\Message
{
    /**
     * Output only. Resource name of the user's passcode. It must have the
     * format of `installations/&#42;&#47;users/&#42;&#47;passcode`. For example:
     * `installations/surelock-homes-hq/users/john-watson/passcode`.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Indicates whether this passcode has been assigned, not assigned or is
     * active and ready for use. This field cannot be modified using a standard
     * passcode update operation. To change the value of this field, you must
     * call
     * [`AssignPasscode`][salto.nebula.user.v1.UserService.AssignPasscode].
     * If the value is `NOT_ASSIGNED` it also applies to cases where the
     * assignation process has been initiated, but not completed.
     *
     * Generated from protobuf field <code>.salto.nebula.user.v1.Passcode.State state = 2;</code>
     */
    protected $state = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           Output only. Resource name of the user's passcode. It must have the
     *           format of `installations/&#42;&#47;users/&#42;&#47;passcode`. For example:
     *           `installations/surelock-homes-hq/users/john-watson/passcode`.
     *     @type int $state
     *           Indicates whether this passcode has been assigned, not assigned or is
     *           active and ready for use. This field cannot be modified using a standard
     *           passcode update operation. To change the value of this field, you must
     *           call
     *           [`AssignPasscode`][salto.nebula.user.v1.UserService.AssignPasscode].
     *           If the value is `NOT_ASSIGNED` it also applies to cases where the
     *           assignation process has been initiated, but not completed.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Saltoapis\Nebula\User\V1\User::initOnce();
        parent::__construct($data);
    }

    /**
     * Output only. Resource name of the user's passcode. It must have the
     * format of `installations/&#42;&#47;users/&#42;&#47;passcode`. For example:
     * `installations/surelock-homes-hq/users/john-watson/passcode`.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Output only. Resource name of the user's passcode. It must have the
     * format of `installations/&#42;&#47;users/&#42;&#47;passcode`. For example:
     * `installations/surelock-homes-hq/users/john-watson/passcode`.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Indicates whether this passcode has been assigned, not assigned or is
     * active and ready for use. This field cannot be modified using a standard
     * passcode update operation. To change the value of this field, you must
     * call
     * [`AssignPasscode`][salto.nebula.user.v1.UserService.AssignPasscode].
     * If the value is `NOT_ASSIGNED` it also applies to cases where the
     * assignation process has been initiated, but not completed.
     *
     * Generated from protobuf field <code>.salto.nebula.user.v1.Passcode.State state = 2;</code>
     * @return int
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * Indicates whether this passcode has been assigned, not assigned or is
     * active and ready for use. This field cannot be modified using a standard
     * passcode update operation. To change the value of this field, you must
     * call
     * [`AssignPasscode`][salto.nebula.user.v1.UserService.AssignPasscode].
     * If the value is `NOT_ASSIGNED` it also applies to cases where the
     * assignation process has been initiated, but not completed.
     *
     * Generated from protobuf field <code>.salto.nebula.user.v1.Passcode.State state = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setState($var)
    {
        GPBUtil::checkEnum($var, \Saltoapis\Nebula\User\V1\Passcode\State::class);
        $this->state = $var;

        return $this;
    }

}

