<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: salto/nebula/booking/v1/booking.proto

namespace Saltoapis\Nebula\Booking\V1\Booking;

use UnexpectedValueException;

/**
 * State for a booking.
 *
 * Protobuf type <code>salto.nebula.booking.v1.Booking.State</code>
 */
class State
{
    /**
     * Sentinel value used to indicate that the state is unknown, omitted,
     * or is not applicable.
     *
     * Generated from protobuf enum <code>STATE_UNSPECIFIED = 0;</code>
     */
    const STATE_UNSPECIFIED = 0;
    /**
     * The booking is scheduled but the user has not yet checked in.
     *
     * Generated from protobuf enum <code>SCHEDULED = 1;</code>
     */
    const SCHEDULED = 1;
    /**
     * The booking is checked in.
     *
     * Generated from protobuf enum <code>CHECKED_IN = 2;</code>
     */
    const CHECKED_IN = 2;
    /**
     * The booking is checked out.
     *
     * Generated from protobuf enum <code>CHECKED_OUT = 3;</code>
     */
    const CHECKED_OUT = 3;

    private static $valueToName = [
        self::STATE_UNSPECIFIED => 'STATE_UNSPECIFIED',
        self::SCHEDULED => 'SCHEDULED',
        self::CHECKED_IN => 'CHECKED_IN',
        self::CHECKED_OUT => 'CHECKED_OUT',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

