<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: salto/nebula/event/v1/types.proto

namespace Saltoapis\Nebula\Event\V1\AccessPointUnlocked;

use UnexpectedValueException;

/**
 * Direction of passage through an access point.
 *
 * Protobuf type <code>salto.nebula.event.v1.AccessPointUnlocked.Direction</code>
 */
class Direction
{
    /**
     * Direction is not specified. Used for remote opening.
     *
     * Generated from protobuf enum <code>DIRECTION_UNSPECIFIED = 0;</code>
     */
    const DIRECTION_UNSPECIFIED = 0;
    /**
     * Credential used to gain access from outside to inside.
     *
     * Generated from protobuf enum <code>ENTRY = 1;</code>
     */
    const ENTRY = 1;
    /**
     * Credential used to leave from inside to outside.
     *
     * Generated from protobuf enum <code>EXIT = 2;</code>
     */
    const PBEXIT = 2;

    private static $valueToName = [
        self::DIRECTION_UNSPECIFIED => 'DIRECTION_UNSPECIFIED',
        self::ENTRY => 'ENTRY',
        self::PBEXIT => 'EXIT',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            $pbconst =  __CLASS__. '::PB' . strtoupper($name);
            if (!defined($pbconst)) {
                throw new UnexpectedValueException(sprintf(
                        'Enum %s has no value defined for name %s', __CLASS__, $name));
            }
            return constant($pbconst);
        }
        return constant($const);
    }
}

