<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: salto/nebula/intercomadaptor/v1/intercom_adaptor.proto

namespace Saltoapis\Nebula\IntercomAdaptor\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The metadata message for [`ConfigureIntercomAdaptor`][salto.nebula.intercomadaptor.v1.IntercomAdaptorService.ConfigureIntercomAdaptor]
 *
 * Generated from protobuf message <code>salto.nebula.intercomadaptor.v1.ConfigureIntercomAdaptorMetadata</code>
 */
class ConfigureIntercomAdaptorMetadata extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Saltoapis\Nebula\IntercomAdaptor\V1\IntercomAdaptor::initOnce();
        parent::__construct($data);
    }

}

