<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: salto/nebula/intercomadaptor/v1/intercom_adaptor.proto

namespace Saltoapis\Nebula\IntercomAdaptor\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The request message for [CreateIntercomAdaptor][salto.nebula.intercomadaptor.v1.IntercomAdaptorService.CreateIntercomAdaptor]
 *
 * Generated from protobuf message <code>salto.nebula.intercomadaptor.v1.CreateIntercomAdaptorRequest</code>
 */
class CreateIntercomAdaptorRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Resource name of the parent resource where to create the intercom adaptor. For
     * example, `installations/surelock-homes-hq`.
     *
     * Generated from protobuf field <code>string parent = 1;</code>
     */
    protected $parent = '';
    /**
     * The intercom adaptor ID to use for this intercom adaptor. In case it's empty the
     * server will autogenerate a unique identifier.
     *
     * Generated from protobuf field <code>optional string intercom_adaptor_id = 2;</code>
     */
    protected $intercom_adaptor_id = null;
    /**
     * The intercom adaptor resource to be created. Client must not set the
     * `IntercomAdaptor.name` field.
     *
     * Generated from protobuf field <code>.salto.nebula.intercomadaptor.v1.IntercomAdaptor intercom_adaptor = 3;</code>
     */
    protected $intercom_adaptor = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $parent
     *           Resource name of the parent resource where to create the intercom adaptor. For
     *           example, `installations/surelock-homes-hq`.
     *     @type string $intercom_adaptor_id
     *           The intercom adaptor ID to use for this intercom adaptor. In case it's empty the
     *           server will autogenerate a unique identifier.
     *     @type \Saltoapis\Nebula\IntercomAdaptor\V1\IntercomAdaptor $intercom_adaptor
     *           The intercom adaptor resource to be created. Client must not set the
     *           `IntercomAdaptor.name` field.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Saltoapis\Nebula\IntercomAdaptor\V1\IntercomAdaptor::initOnce();
        parent::__construct($data);
    }

    /**
     * Resource name of the parent resource where to create the intercom adaptor. For
     * example, `installations/surelock-homes-hq`.
     *
     * Generated from protobuf field <code>string parent = 1;</code>
     * @return string
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * Resource name of the parent resource where to create the intercom adaptor. For
     * example, `installations/surelock-homes-hq`.
     *
     * Generated from protobuf field <code>string parent = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setParent($var)
    {
        GPBUtil::checkString($var, True);
        $this->parent = $var;

        return $this;
    }

    /**
     * The intercom adaptor ID to use for this intercom adaptor. In case it's empty the
     * server will autogenerate a unique identifier.
     *
     * Generated from protobuf field <code>optional string intercom_adaptor_id = 2;</code>
     * @return string
     */
    public function getIntercomAdaptorId()
    {
        return isset($this->intercom_adaptor_id) ? $this->intercom_adaptor_id : '';
    }

    public function hasIntercomAdaptorId()
    {
        return isset($this->intercom_adaptor_id);
    }

    public function clearIntercomAdaptorId()
    {
        unset($this->intercom_adaptor_id);
    }

    /**
     * The intercom adaptor ID to use for this intercom adaptor. In case it's empty the
     * server will autogenerate a unique identifier.
     *
     * Generated from protobuf field <code>optional string intercom_adaptor_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setIntercomAdaptorId($var)
    {
        GPBUtil::checkString($var, True);
        $this->intercom_adaptor_id = $var;

        return $this;
    }

    /**
     * The intercom adaptor resource to be created. Client must not set the
     * `IntercomAdaptor.name` field.
     *
     * Generated from protobuf field <code>.salto.nebula.intercomadaptor.v1.IntercomAdaptor intercom_adaptor = 3;</code>
     * @return \Saltoapis\Nebula\IntercomAdaptor\V1\IntercomAdaptor|null
     */
    public function getIntercomAdaptor()
    {
        return $this->intercom_adaptor;
    }

    public function hasIntercomAdaptor()
    {
        return isset($this->intercom_adaptor);
    }

    public function clearIntercomAdaptor()
    {
        unset($this->intercom_adaptor);
    }

    /**
     * The intercom adaptor resource to be created. Client must not set the
     * `IntercomAdaptor.name` field.
     *
     * Generated from protobuf field <code>.salto.nebula.intercomadaptor.v1.IntercomAdaptor intercom_adaptor = 3;</code>
     * @param \Saltoapis\Nebula\IntercomAdaptor\V1\IntercomAdaptor $var
     * @return $this
     */
    public function setIntercomAdaptor($var)
    {
        GPBUtil::checkMessage($var, \Saltoapis\Nebula\IntercomAdaptor\V1\IntercomAdaptor::class);
        $this->intercom_adaptor = $var;

        return $this;
    }

}

