<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: salto/nebula/installation/v1/installation.proto

namespace Saltoapis\Nebula\Installation\V1\Installation;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The partner info object.
 *
 * Generated from protobuf message <code>salto.nebula.installation.v1.Installation.PartnerInfo</code>
 */
class PartnerInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * The identifier of the partner who created the installation.
     *
     * Generated from protobuf field <code>string partner_id = 1;</code>
     */
    protected $partner_id = '';
    /**
     * The currency code the partner used for the installation (ISO 4217 format).
     *
     * Generated from protobuf field <code>string currency_code = 2;</code>
     */
    protected $currency_code = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $partner_id
     *           The identifier of the partner who created the installation.
     *     @type string $currency_code
     *           The currency code the partner used for the installation (ISO 4217 format).
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Saltoapis\Nebula\Installation\V1\Installation::initOnce();
        parent::__construct($data);
    }

    /**
     * The identifier of the partner who created the installation.
     *
     * Generated from protobuf field <code>string partner_id = 1;</code>
     * @return string
     */
    public function getPartnerId()
    {
        return $this->partner_id;
    }

    /**
     * The identifier of the partner who created the installation.
     *
     * Generated from protobuf field <code>string partner_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPartnerId($var)
    {
        GPBUtil::checkString($var, True);
        $this->partner_id = $var;

        return $this;
    }

    /**
     * The currency code the partner used for the installation (ISO 4217 format).
     *
     * Generated from protobuf field <code>string currency_code = 2;</code>
     * @return string
     */
    public function getCurrencyCode()
    {
        return $this->currency_code;
    }

    /**
     * The currency code the partner used for the installation (ISO 4217 format).
     *
     * Generated from protobuf field <code>string currency_code = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCurrencyCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->currency_code = $var;

        return $this;
    }

}

