<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: salto/nebula/event/v1/event.proto

namespace GPBMetadata\Saltoapis\Nebula\Event\V1;

class Event
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Struct::initOnce();
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        $pool->internalAddGeneratedFile(
            '
§
!salto/nebula/event/v1/event.protosalto.nebula.event.v1google/protobuf/timestamp.proto"½
Event
name (	
type (	
resource (	/
create_time (2.google.protobuf.Timestamp.

occur_time (2.google.protobuf.Timestamp%
data (2.google.protobuf.Struct"
GetEventRequest
name (	"l
ListEventsRequest
parent (	
	page_size (

page_token (	
filter (	
order_by (	"[
ListEventsResponse,
events (2.salto.nebula.event.v1.Event
next_page_token (	2Ã
EventServiceP
GetEvent&.salto.nebula.event.v1.GetEventRequest.salto.nebula.event.v1.Eventa

ListEvents(.salto.nebula.event.v1.ListEventsRequest).salto.nebula.event.v1.ListEventsResponseBÏ
com.saltoapis.nebula.event.v1B
EventProtoPZ@github.com/saltoapis-internal/saltoapis-go/nebula/event/v1;eventªSaltoapis.Nebula.Event.V1ÊSaltoapis\\Nebula\\Event\\V1â%GPBMetadata\\Saltoapis\\Nebula\\Event\\V1bproto3'
        , true);

        static::$is_initialized = true;
    }
}

