<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: salto/nebula/electroniclock/v1/electronic_lock.proto

namespace Saltoapis\Nebula\ElectronicLock\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The request message for [CreateElectronicLock][salto.nebula.electroniclock.v1.ElectronicLockService.CreateElectronicLock]
 *
 * Generated from protobuf message <code>salto.nebula.electroniclock.v1.CreateElectronicLockRequest</code>
 */
class CreateElectronicLockRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Resource name of the parent resource where to create the electronic lock. For
     * example, `installations/surelock-homes-hq`.
     *
     * Generated from protobuf field <code>string parent = 1;</code>
     */
    protected $parent = '';
    /**
     * The electronic lock ID to use for this electronic lock. In case it's empty the
     * server will autogenerate a unique identifier.
     *
     * Generated from protobuf field <code>optional string electronic_lock_id = 2;</code>
     */
    protected $electronic_lock_id = null;
    /**
     * The electronic lock resource to be created. Client must not set the
     * `ElectronicLock.name` field.
     *
     * Generated from protobuf field <code>.salto.nebula.electroniclock.v1.ElectronicLock electronic_lock = 3;</code>
     */
    protected $electronic_lock = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $parent
     *           Resource name of the parent resource where to create the electronic lock. For
     *           example, `installations/surelock-homes-hq`.
     *     @type string $electronic_lock_id
     *           The electronic lock ID to use for this electronic lock. In case it's empty the
     *           server will autogenerate a unique identifier.
     *     @type \Saltoapis\Nebula\ElectronicLock\V1\ElectronicLock $electronic_lock
     *           The electronic lock resource to be created. Client must not set the
     *           `ElectronicLock.name` field.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Saltoapis\Nebula\ElectronicLock\V1\ElectronicLock::initOnce();
        parent::__construct($data);
    }

    /**
     * Resource name of the parent resource where to create the electronic lock. For
     * example, `installations/surelock-homes-hq`.
     *
     * Generated from protobuf field <code>string parent = 1;</code>
     * @return string
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * Resource name of the parent resource where to create the electronic lock. For
     * example, `installations/surelock-homes-hq`.
     *
     * Generated from protobuf field <code>string parent = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setParent($var)
    {
        GPBUtil::checkString($var, True);
        $this->parent = $var;

        return $this;
    }

    /**
     * The electronic lock ID to use for this electronic lock. In case it's empty the
     * server will autogenerate a unique identifier.
     *
     * Generated from protobuf field <code>optional string electronic_lock_id = 2;</code>
     * @return string
     */
    public function getElectronicLockId()
    {
        return isset($this->electronic_lock_id) ? $this->electronic_lock_id : '';
    }

    public function hasElectronicLockId()
    {
        return isset($this->electronic_lock_id);
    }

    public function clearElectronicLockId()
    {
        unset($this->electronic_lock_id);
    }

    /**
     * The electronic lock ID to use for this electronic lock. In case it's empty the
     * server will autogenerate a unique identifier.
     *
     * Generated from protobuf field <code>optional string electronic_lock_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setElectronicLockId($var)
    {
        GPBUtil::checkString($var, True);
        $this->electronic_lock_id = $var;

        return $this;
    }

    /**
     * The electronic lock resource to be created. Client must not set the
     * `ElectronicLock.name` field.
     *
     * Generated from protobuf field <code>.salto.nebula.electroniclock.v1.ElectronicLock electronic_lock = 3;</code>
     * @return \Saltoapis\Nebula\ElectronicLock\V1\ElectronicLock|null
     */
    public function getElectronicLock()
    {
        return $this->electronic_lock;
    }

    public function hasElectronicLock()
    {
        return isset($this->electronic_lock);
    }

    public function clearElectronicLock()
    {
        unset($this->electronic_lock);
    }

    /**
     * The electronic lock resource to be created. Client must not set the
     * `ElectronicLock.name` field.
     *
     * Generated from protobuf field <code>.salto.nebula.electroniclock.v1.ElectronicLock electronic_lock = 3;</code>
     * @param \Saltoapis\Nebula\ElectronicLock\V1\ElectronicLock $var
     * @return $this
     */
    public function setElectronicLock($var)
    {
        GPBUtil::checkMessage($var, \Saltoapis\Nebula\ElectronicLock\V1\ElectronicLock::class);
        $this->electronic_lock = $var;

        return $this;
    }

}

