<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: salto/nebula/electroniclock/v1/electronic_lock.proto

namespace Saltoapis\Nebula\ElectronicLock\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The response message for [`GenerateAuthorizationToken`][salto.nebula.electroniclock.v1.ElectronicLockService.GenerateAuthorizationToken]
 *
 * Generated from protobuf message <code>salto.nebula.electroniclock.v1.GenerateAuthorizationTokenResponse</code>
 */
class GenerateAuthorizationTokenResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Authorization token to be used for connecting to an electronic lock.
     *
     * Generated from protobuf field <code>bytes authorization_token = 1;</code>
     */
    protected $authorization_token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $authorization_token
     *           Authorization token to be used for connecting to an electronic lock.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Saltoapis\Nebula\ElectronicLock\V1\ElectronicLock::initOnce();
        parent::__construct($data);
    }

    /**
     * Authorization token to be used for connecting to an electronic lock.
     *
     * Generated from protobuf field <code>bytes authorization_token = 1;</code>
     * @return string
     */
    public function getAuthorizationToken()
    {
        return $this->authorization_token;
    }

    /**
     * Authorization token to be used for connecting to an electronic lock.
     *
     * Generated from protobuf field <code>bytes authorization_token = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAuthorizationToken($var)
    {
        GPBUtil::checkString($var, False);
        $this->authorization_token = $var;

        return $this;
    }

}

