<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: salto/nebula/electroniclock/v1/electronic_lock.proto

namespace Saltoapis\Nebula\ElectronicLock\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The response message for [ListElectronicLocks][salto.nebula.electroniclock.v1.ElectronicLockService.ListElectronicLocks]
 *
 * Generated from protobuf message <code>salto.nebula.electroniclock.v1.ListElectronicLocksResponse</code>
 */
class ListElectronicLocksResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The field name should match the noun `electronic_locks` in the method name. There
     * will be a maximum number of items returned based on the `page_size` field
     * in the request.
     *
     * Generated from protobuf field <code>repeated .salto.nebula.electroniclock.v1.ElectronicLock electronic_locks = 1;</code>
     */
    private $electronic_locks;
    /**
     * Token to retrieve the next page of results, or empty if there are no more
     * results in the list.
     *
     * Generated from protobuf field <code>string next_page_token = 2;</code>
     */
    protected $next_page_token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Saltoapis\Nebula\ElectronicLock\V1\ElectronicLock>|\Google\Protobuf\Internal\RepeatedField $electronic_locks
     *           The field name should match the noun `electronic_locks` in the method name. There
     *           will be a maximum number of items returned based on the `page_size` field
     *           in the request.
     *     @type string $next_page_token
     *           Token to retrieve the next page of results, or empty if there are no more
     *           results in the list.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Saltoapis\Nebula\ElectronicLock\V1\ElectronicLock::initOnce();
        parent::__construct($data);
    }

    /**
     * The field name should match the noun `electronic_locks` in the method name. There
     * will be a maximum number of items returned based on the `page_size` field
     * in the request.
     *
     * Generated from protobuf field <code>repeated .salto.nebula.electroniclock.v1.ElectronicLock electronic_locks = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getElectronicLocks()
    {
        return $this->electronic_locks;
    }

    /**
     * The field name should match the noun `electronic_locks` in the method name. There
     * will be a maximum number of items returned based on the `page_size` field
     * in the request.
     *
     * Generated from protobuf field <code>repeated .salto.nebula.electroniclock.v1.ElectronicLock electronic_locks = 1;</code>
     * @param array<\Saltoapis\Nebula\ElectronicLock\V1\ElectronicLock>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setElectronicLocks($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Saltoapis\Nebula\ElectronicLock\V1\ElectronicLock::class);
        $this->electronic_locks = $arr;

        return $this;
    }

    /**
     * Token to retrieve the next page of results, or empty if there are no more
     * results in the list.
     *
     * Generated from protobuf field <code>string next_page_token = 2;</code>
     * @return string
     */
    public function getNextPageToken()
    {
        return $this->next_page_token;
    }

    /**
     * Token to retrieve the next page of results, or empty if there are no more
     * results in the list.
     *
     * Generated from protobuf field <code>string next_page_token = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNextPageToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->next_page_token = $var;

        return $this;
    }

}

